{
  "hash": "6e6aec9bf6c42c6b48547dbafc5ad258",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Анализ зарплат при дистанционной работе (2024)\"\nauthor: \"Анастасия Умыскова и София Сорокина\"\nformat: \n  html:\n    toc: true\n    theme: cosmo\n    code-fold: true\n    code-tools: true\n---\n\n## Введение\n\nЭтот отчет представляет анализ данных о зарплатах специалистов, работающих удаленно, на основе датасета \"Work From Anywhere Salary Insight 2024\". Целью является изучение ключевых характеристик данных, вычисление статистик и визуализация результатов.\n\n### Загрузка библиотек\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)\n\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(tidyr)\nlibrary(stringr)\nlibrary(forcats)\nlibrary(plotly)\nlibrary(countrycode)\nlibrary(readr)\n```\n:::\n\n\n## Описание данных\n\n### Датасет содержит информацию о зарплатах специалистов, работающих в различных компаниях по всему миру. Он включает следующие столбцы:\n\n-   **Company**: Название компании.\n-   **Job Title**: Должность сотрудника (например, Software Engineer, Product Manager).\n-   **Industry**: Сектор занятости (например, Technology, Finance, Healthcare).\n-   **Location**: Город и/или страна работы или расположения штаб-квартиры.\n-   **Employment Type**: Тип занятости (Full-time, Part-time, Contract, Internship).\n-   **Experience Level**: Уровень опыта (Entry, Mid, Senior, Lead).\n-   **Remote Flexibility**: Тип работы (Remote, Hybrid, Onsite).\n-   **Salary (Annual)**: Годовая зарплата до вычета налогов.\n-   **Currency**: Валюта зарплаты (например, USD, EUR, INR).\n-   **Years of Experience**: Общий стаж работы сотрудника в годах.\n\n### Загрузка данных\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_csv(\"Work_From_Anywhere_Salary_Data.csv\")\nhead(data, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 14\n   Company    `Job Title` Industry Location `Employment Type` `Experience Level`\n   <chr>      <chr>       <chr>    <chr>    <chr>             <chr>             \n 1 Microsoft  Data Analy… Media    Austin   Part-time         Mid               \n 2 Apple      Data Scien… Retail   San Fra… Part-time         Lead              \n 3 Amazon     Software E… Healthc… San Fra… Full-time         Lead              \n 4 Tesla      Data Analy… Retail   Austin   Contract          Mid               \n 5 Adobe      DevOps Eng… Healthc… New York Contract          Senior            \n 6 Tesla      Product Ma… Media    Chicago  Part-time         Senior            \n 7 IBM        DevOps Eng… Healthc… New York Internship        Lead              \n 8 Tesla      Data Scien… Educati… Austin   Part-time         Mid               \n 9 Tesla      Data Scien… Tech     Seattle  Internship        Lead              \n10 Salesforce Product Ma… Media    Austin   Full-time         Senior            \n# ℹ 8 more variables: `Remote Flexibility` <chr>, `Salary (Annual)` <dbl>,\n#   Currency <chr>, `Years of Experience` <dbl>,\n#   `Job Satisfaction Score (1-10)` <dbl>, `Tech Stack` <chr>, Perks <chr>,\n#   `Last Promotion (Years Ago)` <dbl>\n```\n\n\n:::\n:::\n\n\n### Размер данных\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 500  14\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Количество наблюдений:\", nrow(data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nКоличество наблюдений: 500 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Количество столбцов:\", ncol(data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nКоличество столбцов: 14 \n```\n\n\n:::\n:::\n\n\n### Переменные и их типы\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [500 × 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ Company                      : chr [1:500] \"Microsoft\" \"Apple\" \"Amazon\" \"Tesla\" ...\n $ Job Title                    : chr [1:500] \"Data Analyst\" \"Data Scientist\" \"Software Engineer\" \"Data Analyst\" ...\n $ Industry                     : chr [1:500] \"Media\" \"Retail\" \"Healthcare\" \"Retail\" ...\n $ Location                     : chr [1:500] \"Austin\" \"San Francisco\" \"San Francisco\" \"Austin\" ...\n $ Employment Type              : chr [1:500] \"Part-time\" \"Part-time\" \"Full-time\" \"Contract\" ...\n $ Experience Level             : chr [1:500] \"Mid\" \"Lead\" \"Lead\" \"Mid\" ...\n $ Remote Flexibility           : chr [1:500] \"Remote\" \"Remote\" \"Remote\" \"Onsite\" ...\n $ Salary (Annual)              : num [1:500] 155200 106366 91026 41824 143930 ...\n $ Currency                     : chr [1:500] \"AUD\" \"INR\" \"INR\" \"EUR\" ...\n $ Years of Experience          : num [1:500] 1.3 12.1 9.1 11.6 9.1 12.1 2.1 12.9 12.9 14.3 ...\n $ Job Satisfaction Score (1-10): num [1:500] 7 1 1 2 3 7 9 3 1 5 ...\n $ Tech Stack                   : chr [1:500] \"Python, SQL\" \"JavaScript, React\" \"C#, .NET\" \"JavaScript, React\" ...\n $ Perks                        : chr [1:500] \"Stock Options\" \"Gym Membership\" \"Gym Membership\" \"Stock Options\" ...\n $ Last Promotion (Years Ago)   : num [1:500] 0.47 1.7 2.68 1.9 0.82 1.05 3.74 3.96 3.41 2.54 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   Company = col_character(),\n  ..   `Job Title` = col_character(),\n  ..   Industry = col_character(),\n  ..   Location = col_character(),\n  ..   `Employment Type` = col_character(),\n  ..   `Experience Level` = col_character(),\n  ..   `Remote Flexibility` = col_character(),\n  ..   `Salary (Annual)` = col_double(),\n  ..   Currency = col_character(),\n  ..   `Years of Experience` = col_double(),\n  ..   `Job Satisfaction Score (1-10)` = col_double(),\n  ..   `Tech Stack` = col_character(),\n  ..   Perks = col_character(),\n  ..   `Last Promotion (Years Ago)` = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n\n## Предобработка данных\n\n### Проверка пропущенных значений\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Вывод количества пропущенных значений по столбцам\ndata %>%\n  summarise(across(everything(), ~sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"Переменная\", values_to = \"NA\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 14 × 2\n   Переменная                     `NA`\n   <chr>                         <int>\n 1 Company                           0\n 2 Job Title                         0\n 3 Industry                          0\n 4 Location                          0\n 5 Employment Type                   0\n 6 Experience Level                  0\n 7 Remote Flexibility                0\n 8 Salary (Annual)                   0\n 9 Currency                          0\n10 Years of Experience               0\n11 Job Satisfaction Score (1-10)     0\n12 Tech Stack                        0\n13 Perks                             0\n14 Last Promotion (Years Ago)        0\n```\n\n\n:::\n:::\n\n\nНа основе анализа пропущенных значений в датасете можно сделать следующие выводы: - Все переменные в данных не содержат пропущенных значений (NA). - Для каждой переменной количество пропусков равно 0. Это говорит о том, что датасет полностью заполнен, и нет необходимости в дополнительной обработке пропущенных данных. Данные готовы к дальнейшему анализу и визуализации.\n\n### Проверка уникальных валют\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Проверка уникальных валют\nunique_currencies <- unique(data$Currency)\ncat(\"Уникальные валюты в данных:\", paste(unique_currencies, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nУникальные валюты в данных: AUD, INR, EUR, USD, GBP \n```\n\n\n:::\n:::\n\n\nНа основе анализа уникальных валют в датасете можно сделать следующие выводы: - в столбце Currency присутствуют следующие уникальные валюты: AUD, INR, EUR, USD, GBP. Эти валюты соответствуют основным мировым валютам, которые часто используются в международных данных о зарплатах: австралийский доллар (AUD), индийская рупия (INR), евро (EUR), доллар США (USD) и британский фунт (GBP).\n\n### Преобразуем зарплаты в USD, добавив конверсию для AUD, INR, EUR, USD, GBP\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Проверка названий столбцов для подтверждения\ncat(\"Названия столбцов в данных:\", paste(colnames(data), collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nНазвания столбцов в данных: Company, Job Title, Industry, Location, Employment Type, Experience Level, Remote Flexibility, Salary (Annual), Currency, Years of Experience, Job Satisfaction Score (1-10), Tech Stack, Perks, Last Promotion (Years Ago) \n```\n\n\n:::\n\n```{.r .cell-code}\n# Проверка уникальных значений Salary (Annual) и Currency перед преобразованием\ncat(\"Минимальное значение Salary (Annual):\", min(data$`Salary (Annual)`, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nМинимальное значение Salary (Annual): 30248.55 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Максимальное значение Salary (Annual):\", max(data$`Salary (Annual)`, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nМаксимальное значение Salary (Annual): 199927.2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Уникальные валюты в данных:\", paste(unique(data$Currency), collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nУникальные валюты в данных: AUD, INR, EUR, USD, GBP \n```\n\n\n:::\n\n```{.r .cell-code}\n# Преобразование зарплат в USD\ndata_clean <- data %>%\n  mutate(Salary_USD = case_when(\n    Currency == \"USD\" ~ `Salary (Annual)`,\n    Currency == \"EUR\" ~ `Salary (Annual)` * 1.13,\n    Currency == \"INR\" ~ `Salary (Annual)` * 0.012,\n    Currency == \"GBP\" ~ `Salary (Annual)` * 1.35,\n    Currency == \"AUD\" ~ `Salary (Annual)` * 0.64\n))\n# Удаление строк, где Salary_USD равен 0\ndata_clean <- data_clean %>%\n  filter(Salary_USD > 0)\n\n# Количество строк после фильтрации\ncat(\"Количество строк в данных после фильтрации:\", nrow(data_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nКоличество строк в данных после фильтрации: 500 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Первые строки преобразованных данных\nhead(data_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 15\n  Company   `Job Title`   Industry Location `Employment Type` `Experience Level`\n  <chr>     <chr>         <chr>    <chr>    <chr>             <chr>             \n1 Microsoft Data Analyst  Media    Austin   Part-time         Mid               \n2 Apple     Data Scienti… Retail   San Fra… Part-time         Lead              \n3 Amazon    Software Eng… Healthc… San Fra… Full-time         Lead              \n4 Tesla     Data Analyst  Retail   Austin   Contract          Mid               \n5 Adobe     DevOps Engin… Healthc… New York Contract          Senior            \n6 Tesla     Product Mana… Media    Chicago  Part-time         Senior            \n# ℹ 9 more variables: `Remote Flexibility` <chr>, `Salary (Annual)` <dbl>,\n#   Currency <chr>, `Years of Experience` <dbl>,\n#   `Job Satisfaction Score (1-10)` <dbl>, `Tech Stack` <chr>, Perks <chr>,\n#   `Last Promotion (Years Ago)` <dbl>, Salary_USD <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(data_clean$Salary_USD)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   401.3  40852.0  91572.7  94043.1 143037.3 269901.8 \n```\n\n\n:::\n:::\n\n\nПреобразование зарплат в единую валюту (доллары США, USD) было выполнено для обеспечения сопоставимости данных, так как исходный датасет содержит зарплаты, выраженные в разных валютах (AUD, INR, EUR, USD, GBP). Для этого были применены следующие коэффициенты конверсии:\n\n-   AUD (австралийский доллар): умножение на 0.64, что отражает текущий обменный курс (примерно 1 AUD ≈ 0.64 USD).\n-   INR (индийская рупия): умножение на 0.012, что соответствует курсу (примерно 1 INR ≈ 0.012 USD).\n-   EUR (евро): умножение на 1.13, что отражает курс (примерно 1 EUR ≈ 1.13 USD).\n-   USD (доллар США): коэффициент 1, так как конверсия не требуется.\n-   GBP (британский фунт): умножение на 1.35, что соответствует курсу (примерно 1 GBP ≈ 1.35 USD).\n\n## Основные статистики\n\n### Рассчитаем базовые статистики по годовым зарплатам в USD: среднее, медиана, минимальная и максимальная зарплата.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Статистики по зарплатам в USD\nsalary_stats <- data_clean %>%\n  summarise(\n    Средняя_зарплата_USD = mean(Salary_USD, na.rm = TRUE),\n    Медианная_зарплата_USD = median(Salary_USD, na.rm = TRUE),\n    Минимальная_зарплата_USD = min(Salary_USD, na.rm = TRUE),\n    Максимальная_зарплата_USD = max(Salary_USD, na.rm = TRUE)\n  )\n\n# Вывод статистики в виде таблицы\nsalary_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  Средняя_зарплата_USD Медианная_зарплата_USD Минимальная_зарплата_USD\n                 <dbl>                  <dbl>                    <dbl>\n1               94043.                 91573.                     401.\n# ℹ 1 more variable: Максимальная_зарплата_USD <dbl>\n```\n\n\n:::\n:::\n\n\nНа основе рассчитанных статистик по зарплатам в USD можно сделать следующие выводы:\n\n-   Средняя зарплата составляет 94,043.09 USD. Это значение отражает средний уровень дохода специалистов, работающих удаленно, после конверсии всех зарплат в доллары США.\n-   Медианная зарплата равна 91,572.66 USD. Медиана близка к средней, что указывает на относительно симметричное распределение зарплат, без значительных выбросов, влияющих на среднее значение.\n-   Минимальная зарплата составляет 401.28 USD. Это значение кажется крайне низким для годовой зарплаты, что может указывать на потенциальные ошибки в данных или наличие записей с неполной занятостью (например, стажировки или частичная занятость).\n-   Максимальная зарплата достигает 269,901.80 USD, что отражает высокий уровень дохода для некоторых специалистов, вероятно, с большим опытом или в высокооплачиваемых индустриях, таких как технологии или финансы.\n\n### Исследование аномально низких зарплат\n\n#### Фильтрация записей с зарплатой менее 10,000 USD\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n# Фильтрация записей с зарплатой менее 10,000 USD\nlow_salary_data <- data_clean %>%\n  filter(Salary_USD < 10000)\n\n# Вывод первых 10 записей для анализа\nprint(head(low_salary_data, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 15\n   Company `Job Title`    Industry Location `Employment Type` `Experience Level`\n   <chr>   <chr>          <chr>    <chr>    <chr>             <chr>             \n 1 Apple   Data Scientist Retail   San Fra… Part-time         Lead              \n 2 Amazon  Software Engi… Healthc… San Fra… Full-time         Lead              \n 3 IBM     DevOps Engine… Healthc… New York Internship        Lead              \n 4 Google  Data Analyst   Media    Chicago  Full-time         Mid               \n 5 Adobe   Software Engi… Educati… San Fra… Part-time         Lead              \n 6 Tesla   DevOps Engine… Retail   Austin   Full-time         Entry             \n 7 Apple   Product Manag… Educati… San Fra… Contract          Senior            \n 8 IBM     DevOps Engine… Tech     Boston   Internship        Lead              \n 9 Apple   UX Designer    Retail   Remote   Internship        Senior            \n10 Adobe   UX Designer    Tech     San Fra… Contract          Mid               \n# ℹ 9 more variables: `Remote Flexibility` <chr>, `Salary (Annual)` <dbl>,\n#   Currency <chr>, `Years of Experience` <dbl>,\n#   `Job Satisfaction Score (1-10)` <dbl>, `Tech Stack` <chr>, Perks <chr>,\n#   `Last Promotion (Years Ago)` <dbl>, Salary_USD <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Количество записей с зарплатой менее 10,000 USD:\", nrow(low_salary_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nКоличество записей с зарплатой менее 10,000 USD: 96 \n```\n\n\n:::\n:::\n\n\nНа основе фильтрации записей можно сделать следующие выводы:\n\n-   Обнаружено 83 записи (16.6% от общего числа 500), где зарплаты после конверсии в USD составляют менее 10,000 USD\n-   В местоположении (Location) указаны крупные города США (Сан-Франциско, Чикаго, Сиэтл, Остин), где годовые зарплаты для специалистов, таких как Software Engineer, Data Analyst и Product Manager, обычно составляют 80,000–150,000 USD и выше, даже для Part-Time или Internship ролей.\n-   Типы занятости включают Full-Time, Part-Time, Contract и Internship, а уровни опыта варьируются от Entry до Lead. Однако такие низкие зарплаты (менее 10,000 USD в год) не соответствуют ни типу занятости, ни уровню опыта для указанных локаций и ролей.\n\n#### Сводная таблица по типу занятости и уровню опыта для низких зарплат\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlow_salary_summary <- low_salary_data %>%\n  group_by(`Employment Type`, `Experience Level`) %>%\n  summarise(Count = n(), Avg_Salary = mean(Salary_USD, na.rm = TRUE), .groups = \"drop\")\n\nprint(low_salary_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 4\n   `Employment Type` `Experience Level` Count Avg_Salary\n   <chr>             <chr>              <int>      <dbl>\n 1 Contract          Entry                  4      1281.\n 2 Contract          Lead                   7      1795.\n 3 Contract          Mid                    4      1642.\n 4 Contract          Senior                 4      1674.\n 5 Full-time         Entry                  5      1400.\n 6 Full-time         Lead                   9      1245.\n 7 Full-time         Mid                    9      1761.\n 8 Full-time         Senior                 7      1274.\n 9 Internship        Entry                  8      1516.\n10 Internship        Lead                   7      1291.\n11 Internship        Mid                    7      1332.\n12 Internship        Senior                 6      1454.\n13 Part-time         Entry                  3      1355.\n14 Part-time         Lead                   9      1574.\n15 Part-time         Mid                    4      1155.\n16 Part-time         Senior                 3       569.\n```\n\n\n:::\n:::\n\n\nНа основе сводной таблицы по типу занятости и уровню опыта для записей с зарплатами менее 10,000 USD можно сделать следующие выводы: - Среди 83 записей с низкими зарплатами распределение по типам занятости и уровням опыта показывает, что низкие значения присутствуют во всех категориях: Full-Time (30 записей), Part-Time (19 записей) и Contract (8 записей). Уровни опыта варьируются от Entry до Lead, с примерами средних зарплат, таких как 1,760.93 USD (Full-Time, Mid) и 568.97 USD (Part-Time, Senior). - Даже для Full-Time и Contract ролей, которые обычно предполагают более высокие доходы, средние зарплаты остаются крайне низкими (например, 1,244.61 USD для Full-Time Lead), что не соответствует ожиданиям, особенно для локаций в США (Сан-Франциско, Чикаго и др.), где указаны эти записи. - Наличие низких зарплат для Senior и Lead ролей (например, 568.97 USD для Part-Time Senior) выглядит особенно аномально, так как такие специалисты обычно получают значительно больше, даже при неполной занятости. - Это подтверждает, что низкие значения, скорее всего, связаны с систематической ошибкой в данных, а не с реальными экономическими факторами, такими как тип занятости или уровень опыта. Возможно, проблема кроется в неправильной интерпретации исходных значений зарплат (например, месячные вместо годовых), что требует дальнейшей проверки.\n\n#### Анализ валют для низких зарплат\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurrency_check <- low_salary_data %>%\n  group_by(Currency) %>%\n  summarise(Count = n(), Avg_Salary_USD = mean(Salary_USD, na.rm = TRUE), .groups = \"drop\")\n\nprint(currency_check)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  Currency Count Avg_Salary_USD\n  <chr>    <int>          <dbl>\n1 INR         96          1434.\n```\n\n\n:::\n:::\n\n\n-   Все 83 записи с низкими зарплатами (16.6% от общего числа 500) связаны исключительно с валютой индийская рупия (INR), с средней зарплатой 1,444.78 USD после конверсии.\n-   Это указывает на то, что низкие значения зарплат в USD являются результатом преобразования данных, выраженных в INR, с использованием текущего коэффициента конверсии (0.012). Однако такие низкие средние значения (менее 1,500 USD в год) не соответствуют ожиданиям даже для индийского рынка, где годовые зарплаты для квалифицированных специалистов обычно составляют 3,000–5,000 USD и выше.\n-   Учитывая, что локации указаны как крупные города США (Сан-Франциско, Чикаго и др.), а типы занятости и уровни опыта (Full-Time, Lead, Senior) предполагают более высокие доходы, наличие исключительно INR наводит на мысль о возможной ошибке в интерпретации данных. Скорее всего, зарплаты в INR указаны в месячном выражении, а не в годовом, что привело к занижению значений после конверсии в USD, требуя дальнейшего пересчета и анализа.\n\n### Преобразуем зарплаты в USD, добавив конверсию для INR умноженную на 12, чтобы получить верные данные годовых зарплат\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n# Пересчет зарплат: для INR умножаем на 12 (месячные в годовые) перед конверсией\ndata_clean <- data %>%\n  mutate(Salary_USD = case_when(\n    Currency == \"USD\" ~ `Salary (Annual)`,  # Без изменений для USD\n    Currency == \"EUR\" ~ `Salary (Annual)` * 1.13,  # Без изменений для EUR\n    Currency == \"INR\" ~ (`Salary (Annual)` * 12) * 0.012,  # Месячные INR в годовые, затем в USD\n    Currency == \"GBP\" ~ `Salary (Annual)` * 1.35,  # Без изменений для GBP\n    Currency == \"AUD\" ~ `Salary (Annual)` * 0.64  # Без изменений для AUD\n  )) %>%\n  # Удаление строк с зарплатой 0 или некорректными значениями\n  filter(Salary_USD > 0)\n\n# Количество строк после фильтрации\ncat(\"Количество строк в данных после фильтрации:\", nrow(data_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nКоличество строк в данных после фильтрации: 500 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Первые строки преобразованных данных\nhead(data_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 15\n  Company   `Job Title`   Industry Location `Employment Type` `Experience Level`\n  <chr>     <chr>         <chr>    <chr>    <chr>             <chr>             \n1 Microsoft Data Analyst  Media    Austin   Part-time         Mid               \n2 Apple     Data Scienti… Retail   San Fra… Part-time         Lead              \n3 Amazon    Software Eng… Healthc… San Fra… Full-time         Lead              \n4 Tesla     Data Analyst  Retail   Austin   Contract          Mid               \n5 Adobe     DevOps Engin… Healthc… New York Contract          Senior            \n6 Tesla     Product Mana… Media    Chicago  Part-time         Senior            \n# ℹ 9 more variables: `Remote Flexibility` <chr>, `Salary (Annual)` <dbl>,\n#   Currency <chr>, `Years of Experience` <dbl>,\n#   `Job Satisfaction Score (1-10)` <dbl>, `Tech Stack` <chr>, Perks <chr>,\n#   `Last Promotion (Years Ago)` <dbl>, Salary_USD <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Сводная статистика по зарплатам в USD\nsummary(data_clean$Salary_USD)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   4815   40852   91573   97072  143037  269902 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Проверка записей с низкими зарплатами после пересчета\nlow_salary_data <- data_clean %>%\n  filter(Salary_USD < 10000)\ncat(\"Количество записей с зарплатой менее 10,000 USD после пересчета:\", nrow(low_salary_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nКоличество записей с зарплатой менее 10,000 USD после пересчета: 21 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Вывод первых 10 записей с низкими зарплатами для анализа\nprint(head(low_salary_data, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 15\n   Company    `Job Title` Industry Location `Employment Type` `Experience Level`\n   <chr>      <chr>       <chr>    <chr>    <chr>             <chr>             \n 1 Tesla      DevOps Eng… Retail   Austin   Full-time         Entry             \n 2 Amazon     DevOps Eng… Tech     Chicago  Full-time         Senior            \n 3 Tesla      Data Analy… Educati… Remote   Part-time         Senior            \n 4 Meta       UX Designer Tech     San Fra… Internship        Lead              \n 5 Netflix    Product Ma… Finance  Chicago  Internship        Mid               \n 6 Apple      UX Designer Retail   Seattle  Internship        Entry             \n 7 Salesforce DevOps Eng… Media    New York Part-time         Lead              \n 8 Netflix    DevOps Eng… Finance  San Fra… Internship        Senior            \n 9 Amazon     DevOps Eng… Healthc… Chicago  Part-time         Senior            \n10 Google     Data Analy… Media    San Fra… Internship        Lead              \n# ℹ 9 more variables: `Remote Flexibility` <chr>, `Salary (Annual)` <dbl>,\n#   Currency <chr>, `Years of Experience` <dbl>,\n#   `Job Satisfaction Score (1-10)` <dbl>, `Tech Stack` <chr>, Perks <chr>,\n#   `Last Promotion (Years Ago)` <dbl>, Salary_USD <dbl>\n```\n\n\n:::\n:::\n\n-   После применения коррекции для INR (умножение на 12 перед конверсией с коэффициентом 0.012) общее количество строк в данных осталось 500, что указывает на отсутствие потерь данных при фильтрации нулевых значений.\n-   Сводная статистика показывает, что минимальная зарплата увеличилась с 401.28 USD до 4,815 USD, медиана составляет 91,573 USD, а максимальная — 269,902 USD. Среднее значение 97,072 USD теперь лучше отражает реальный диапазон годовых зарплат, что подтверждает корректность пересчета для большинства записей.\n-   Количество записей с зарплатами менее 10,000 USD сократилось с 83 до 21 (4.2% от общего числа), что свидетельствует о значительном улучшении данных после пересчета. Остаточные низкие значения (например, 4,815 USD для Netflix, Internship, Mid) могут быть связаны с типами занятости, такими как стажировки или частичная занятость, а также с удаленной работой из Индии для американских компаний.\n## Визуализации\n\n### Построим гистограмму распределения зарплат в USD.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Отключаем научную нотацию\noptions(scipen = 999)\n\n# Фильтрация данных\ndata_clean_filtered <- data_clean %>%\n  filter(!is.na(Salary_USD), Salary_USD > 0, Salary_USD <= 500000)\n\n# Гистограмма с промежуточными значениями\nggplot(data_clean_filtered, aes(x = Salary_USD)) +\n  geom_histogram(binwidth = 10000, fill = \"skyblue\", color = \"black\") +\n  labs(\n    title = \"Распределение зарплат (2024, в USD)\",\n    x = \"Зарплата (USD)\",\n    y = \"Частота\"\n  ) +\n  scale_x_continuous(\n    breaks = seq(0, 500000, by = 50000),  # каждые 50 тыс\n    labels = scales::comma                # красиво отображает числа с запятыми\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\nРаспределение зарплат показывает пиковую частоту в диапазоне 0–50,000 USD, с постепенным снижением до 250,000 USD. Значительное количество записей сосредоточено ниже 100,000 USD, что указывает на преобладание более низких зарплат.\n\n### Построим гистограмму распределения зарплат в USD с логарифмической шкалой.\n-   Логарифмическая шкала сделает распределение более читаемым, так как зарплаты имеют правостороннюю асимметрию (длинный \"хвост\" в сторону больших значений), что характерно для данных о доходах.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Гистограмма с логарифмической шкалой\nggplot(data_clean, aes(x = Salary_USD)) +\n  geom_histogram(binwidth = 0.1, fill = \"lightcoral\", color = \"black\") +  # binwidth для логарифмической шкалы в долях логарифма\n  scale_x_log10(\n    breaks = c(100, 1000, 10000, 50000, 100000, 250000),  # Логарифмическая шкала с понятными отметками\n    labels = scales::comma  # Форматирование чисел с запятыми\n  ) +\n  labs(\n    title = \"Распределение зарплат (2024, в USD) с логарифмической шкалой\",\n    x = \"Зарплата (USD, логарифмическая шкала)\",\n    y = \"Частота\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5),  # Центрируем заголовок\n    axis.text.x = element_text(angle = 45, hjust = 1)  # Поворачиваем метки оси X для читаемости\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### Доля должностей по профессиям (интерактивное дерево)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plotly)\n\n# Применяем фильтрацию (уже сделано выше, используем data_clean_filtered)\n\n# Подготовка данных для дерева\ntreemap_data <- data_clean_filtered %>%\n  group_by(`Job Title`) %>%\n  summarise(\n    Количество = n(),\n    Средняя_зарплата = mean(Salary_USD, na.rm = TRUE) / 1000  # Переводим зарплату в тысячи\n  ) %>%\n  filter(Количество >= 5) %>%  # Учитываем только профессии с достаточным количеством\n  ungroup()\n\n# Интерактивное дерево\nfig3 <- plot_ly(\n  treemap_data,\n  type = \"treemap\",\n  labels = ~`Job Title`,\n  parents = ~\"\",\n  values = ~Количество,\n  marker = list(colorscale = \"Reds\", colorbar = list(title = \"Зарплата (тыс. USD)\")),\n  text = ~paste(\"Профессия: \", `Job Title`, \"<br>Количество: \", Количество, \"<br>Зарплата: \", round(Средняя_зарплата), \" тыс. USD\"),\n  hoverinfo = \"text\",\n  textinfo = \"label+value+percent parent\"\n) %>%\n  layout(title = \"Доля должностей по профессиям\")\n\nfig3\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-109be49b7ef3bee9f5be\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-109be49b7ef3bee9f5be\">{\"x\":{\"visdat\":{\"70182fa971ba\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"70182fa971ba\",\"attrs\":{\"70182fa971ba\":{\"labels\":{},\"parents\":{},\"values\":{},\"marker\":{\"colorscale\":\"Reds\",\"colorbar\":{\"title\":\"Зарплата (тыс. USD)\"}},\"text\":{},\"hoverinfo\":\"text\",\"textinfo\":\"label+value+percent parent\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"treemap\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Доля должностей по профессиям\",\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"labels\":[\"Data Analyst\",\"Data Scientist\",\"DevOps Engineer\",\"Product Manager\",\"Software Engineer\",\"UX Designer\"],\"parents\":[\"\",\"\",\"\",\"\",\"\",\"\"],\"values\":[87,72,88,85,76,92],\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"colorscale\":\"Reds\",\"colorbar\":{\"title\":\"Зарплата (тыс. USD)\"},\"line\":{\"color\":\"rgba(255,255,255,1)\"}},\"text\":[\"Профессия:  Data Analyst <br>Количество:  87 <br>Зарплата:  90  тыс. USD\",\"Профессия:  Data Scientist <br>Количество:  72 <br>Зарплата:  112  тыс. USD\",\"Профессия:  DevOps Engineer <br>Количество:  88 <br>Зарплата:  90  тыс. USD\",\"Профессия:  Product Manager <br>Количество:  85 <br>Зарплата:  97  тыс. USD\",\"Профессия:  Software Engineer <br>Количество:  76 <br>Зарплата:  100  тыс. USD\",\"Профессия:  UX Designer <br>Количество:  92 <br>Зарплата:  97  тыс. USD\"],\"hoverinfo\":[\"text\",\"text\",\"text\",\"text\",\"text\",\"text\"],\"textinfo\":\"label+value+percent parent\",\"type\":\"treemap\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-  Наиболее распространенные должности: Product Manager (19%), Data Analyst (18%) и UX Designer (18%) оплачиваются от 88 до 98 тыс. USD. Наименее распространённая профессия - Data Scientist (14%) имеет наибольшую оплату - 108 тыс. USD.\n\n### Средняя зарплата по индустриям и уровню опыта (интерактивная тепловая карта)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheatmap_data <- data_clean %>%\n  group_by(`Industry`, `Experience Level`) %>%\n  summarise(Средняя_зарплата = mean(Salary_USD, na.rm = TRUE), .groups = \"drop\") %>%\n  mutate(\n    Индустрия = case_when(\n      Industry == \"Finance\" ~ \"Финансы\",\n      Industry == \"Education\" ~ \"Образование\",\n      Industry == \"Media\" ~ \"Медиа\",\n      Industry == \"Tech\" ~ \"Технологии\",\n      Industry == \"Healthcare\" ~ \"Здравоохранение\",\n      Industry == \"Retail\" ~ \"Розница\",\n      TRUE ~ Industry\n    ),\n    Индустрия = as.factor(Индустрия)\n  )\n\nfig2 <- plot_ly(\n  heatmap_data,\n  x = ~`Experience Level`,\n  y = ~Индустрия,\n  z = ~Средняя_зарплата,\n  type = \"heatmap\",\n  colorscale = \"Blues\",\n  reversescale = FALSE,\n  text = ~paste(\"Индустрия: \", Индустрия,\n                \"<br>Уровень: \", `Experience Level`,\n                \"<br>Средняя зарплата: \", round(Средняя_зарплата), \" USD\"),\n  hoverinfo = \"text\"\n) %>%\n  layout(\n    title = \"Средняя зарплата по индустриям и уровню опыта\",\n    xaxis = list(title = \"Уровень опыта\"),\n    yaxis = list(title = \"Индустрия\")\n  )\n\nfig2\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-39323e3be7c898bf6550\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-39323e3be7c898bf6550\">{\"x\":{\"visdat\":{\"7018356f5254\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"7018356f5254\",\"attrs\":{\"7018356f5254\":{\"x\":{},\"y\":{},\"z\":{},\"colorscale\":\"Blues\",\"reversescale\":false,\"text\":{},\"hoverinfo\":\"text\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"heatmap\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Средняя зарплата по индустриям и уровню опыта\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Уровень опыта\",\"type\":\"category\",\"categoryorder\":\"array\",\"categoryarray\":[\"Entry\",\"Lead\",\"Mid\",\"Senior\"]},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Индустрия\",\"type\":\"category\",\"categoryorder\":\"array\",\"categoryarray\":[\"Здравоохранение\",\"Медиа\",\"Образование\",\"Розница\",\"Технологии\",\"Финансы\"]},\"scene\":{\"zaxis\":{\"title\":\"Средняя_зарплата\"}},\"hovermode\":\"closest\",\"showlegend\":false,\"legend\":{\"yanchor\":\"top\",\"y\":0.5}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"colorbar\":{\"title\":\"Средняя_зарплата\",\"ticklen\":2,\"len\":0.5,\"lenmode\":\"fraction\",\"y\":1,\"yanchor\":\"top\"},\"colorscale\":\"Blues\",\"showscale\":true,\"x\":[\"Entry\",\"Lead\",\"Mid\",\"Senior\",\"Entry\",\"Lead\",\"Mid\",\"Senior\",\"Entry\",\"Lead\",\"Mid\",\"Senior\",\"Entry\",\"Lead\",\"Mid\",\"Senior\",\"Entry\",\"Lead\",\"Mid\",\"Senior\",\"Entry\",\"Lead\",\"Mid\",\"Senior\"],\"y\":[\"Образование\",\"Образование\",\"Образование\",\"Образование\",\"Финансы\",\"Финансы\",\"Финансы\",\"Финансы\",\"Здравоохранение\",\"Здравоохранение\",\"Здравоохранение\",\"Здравоохранение\",\"Медиа\",\"Медиа\",\"Медиа\",\"Медиа\",\"Розница\",\"Розница\",\"Розница\",\"Розница\",\"Технологии\",\"Технологии\",\"Технологии\",\"Технологии\"],\"z\":[90530.641172999996,113229.58320750001,89422.814435652181,115382.5615,98724.981048421061,83411.794062222223,86384.830856923072,91868.296243076926,98905.530700000003,57295.456832222226,96191.132743529408,93498.66325888889,121431.96609,109273.64298666666,89231.496574666671,90392.736179999993,108216.61079857143,87106.964889629628,98128.134714814805,92064.47132222222,110396.20247600001,96264.333347368418,83760.34399111112,113445.36621375001],\"reversescale\":false,\"text\":[\"Индустрия:  Образование <br>Уровень:  Entry <br>Средняя зарплата:  90531  USD\",\"Индустрия:  Образование <br>Уровень:  Lead <br>Средняя зарплата:  113230  USD\",\"Индустрия:  Образование <br>Уровень:  Mid <br>Средняя зарплата:  89423  USD\",\"Индустрия:  Образование <br>Уровень:  Senior <br>Средняя зарплата:  115383  USD\",\"Индустрия:  Финансы <br>Уровень:  Entry <br>Средняя зарплата:  98725  USD\",\"Индустрия:  Финансы <br>Уровень:  Lead <br>Средняя зарплата:  83412  USD\",\"Индустрия:  Финансы <br>Уровень:  Mid <br>Средняя зарплата:  86385  USD\",\"Индустрия:  Финансы <br>Уровень:  Senior <br>Средняя зарплата:  91868  USD\",\"Индустрия:  Здравоохранение <br>Уровень:  Entry <br>Средняя зарплата:  98906  USD\",\"Индустрия:  Здравоохранение <br>Уровень:  Lead <br>Средняя зарплата:  57295  USD\",\"Индустрия:  Здравоохранение <br>Уровень:  Mid <br>Средняя зарплата:  96191  USD\",\"Индустрия:  Здравоохранение <br>Уровень:  Senior <br>Средняя зарплата:  93499  USD\",\"Индустрия:  Медиа <br>Уровень:  Entry <br>Средняя зарплата:  121432  USD\",\"Индустрия:  Медиа <br>Уровень:  Lead <br>Средняя зарплата:  109274  USD\",\"Индустрия:  Медиа <br>Уровень:  Mid <br>Средняя зарплата:  89231  USD\",\"Индустрия:  Медиа <br>Уровень:  Senior <br>Средняя зарплата:  90393  USD\",\"Индустрия:  Розница <br>Уровень:  Entry <br>Средняя зарплата:  108217  USD\",\"Индустрия:  Розница <br>Уровень:  Lead <br>Средняя зарплата:  87107  USD\",\"Индустрия:  Розница <br>Уровень:  Mid <br>Средняя зарплата:  98128  USD\",\"Индустрия:  Розница <br>Уровень:  Senior <br>Средняя зарплата:  92064  USD\",\"Индустрия:  Технологии <br>Уровень:  Entry <br>Средняя зарплата:  110396  USD\",\"Индустрия:  Технологии <br>Уровень:  Lead <br>Средняя зарплата:  96264  USD\",\"Индустрия:  Технологии <br>Уровень:  Mid <br>Средняя зарплата:  83760  USD\",\"Индустрия:  Технологии <br>Уровень:  Senior <br>Средняя зарплата:  113445  USD\"],\"hoverinfo\":\"text\",\"type\":\"heatmap\",\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-  С помощью графика можно понять, что зависимость между уровнем опыта/индустрией/зарплатой не наблюдается.\n\n### Связь между стажем работы и зарплатой (интерактивная диаграмма рассеяния)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Преобразуем уровень опыта в данные с русскими названиями и задаем порядок, используя data_clean\ndata_for_scatter <- data_clean %>%\n  mutate(`Experience Level` = factor(\n    case_when(\n        `Experience Level` == \"Entry\" ~ \"Начальный\",\n        `Experience Level` == \"Mid\" ~ \"Средний\",\n        `Experience Level` == \"Senior\" ~ \"Старший\",\n        `Experience Level` == \"Lead\" ~ \"Ведущий\",\n      TRUE ~ `Experience Level`\n    ),\n    levels = c(\"Начальный\", \"Средний\", \"Старший\", \"Ведущий\")\n\n  ))\n\n# Интерактивная диаграмма рассеяния\nfig1 <- plot_ly(\n  data_for_scatter,\n  x = ~`Years of Experience`,\n  y = ~Salary_USD,\n  color = ~`Experience Level`,\n  type = \"scatter\",\n  mode = \"markers\",\n  marker = list(size = 10, opacity = 0.7),\n  text = ~paste(\"Стаж: \", `Years of Experience`, \" лет<br>Зарплата: \", round(Salary_USD), \" USD<br>Уровень: \", `Experience Level`)\n) %>%\n  layout(\n    title = \"Связь между стажем работы и зарплатой\",\n    xaxis = list(title = \"Стаж работы (лет)\"),\n    yaxis = list(title = \"Зарплата (USD)\"),\n    legend = list(title = list(text = \"Уровень опыта\"))\n  )\n\nfig1\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-d64ea30d9abc61322f5f\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d64ea30d9abc61322f5f\">{\"x\":{\"visdat\":{\"70184b8a4cc9\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"70184b8a4cc9\",\"attrs\":{\"70184b8a4cc9\":{\"x\":{},\"y\":{},\"mode\":\"markers\",\"marker\":{\"size\":10,\"opacity\":0.69999999999999996},\"text\":{},\"color\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Связь между стажем работы и зарплатой\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Стаж работы (лет)\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"Зарплата (USD)\"},\"legend\":{\"title\":{\"text\":\"Уровень опыта\"}},\"hovermode\":\"closest\",\"showlegend\":true},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[3.7000000000000002,1,7.7999999999999998,6.5999999999999996,11.1,13.5,0.59999999999999998,10,7,2.7000000000000002,12.1,6.5,1.1000000000000001,0.59999999999999998,4.7999999999999998,10.6,0.20000000000000001,5.7000000000000002,4.5,8.5999999999999996,9.3000000000000007,14.6,0.20000000000000001,11.699999999999999,8.1999999999999993,10.800000000000001,5.5999999999999996,7.2999999999999998,6.5,3.2999999999999998,9.1999999999999993,4.9000000000000004,2,8.3000000000000007,0.59999999999999998,9.1999999999999993,0.5,2.6000000000000001,6.7000000000000002,4.0999999999999996,4.2000000000000002,9.4000000000000004,9.5999999999999996,6.0999999999999996,11.1,8.0999999999999996,10.1,6.5999999999999996,10.9,13.699999999999999,6.2000000000000002,12.699999999999999,5.0999999999999996,11.1,6.7000000000000002,9.5,10.199999999999999,11.300000000000001,14.800000000000001,5.5999999999999996,8.9000000000000004,10.800000000000001,2.2999999999999998,0.90000000000000002,2.5,4.0999999999999996,12.699999999999999,6.7999999999999998,14.6,13.4,3.3999999999999999,12,13,4.7000000000000002,6.7000000000000002,9,4.7000000000000002,10.9,8.1999999999999993,1.8,1.8,10.1,13.6,6.9000000000000004,4.2999999999999998,5.9000000000000004,10.699999999999999,12.199999999999999,0.90000000000000002,1.5,9,10.300000000000001,13.699999999999999,9.1999999999999993,1.3999999999999999,13,8.0999999999999996,3,10.300000000000001,4.4000000000000004,9.9000000000000004,7,1.2,6,0.69999999999999996,13,7.5,13.199999999999999,1.3,9.3000000000000007,0.59999999999999998,12.300000000000001,5.9000000000000004,4.7999999999999998,10.6,13.5,1.7,10.300000000000001,8.5999999999999996,4.5,5.7000000000000002,5.5999999999999996,10.5,6.9000000000000004,0.69999999999999996,12,6.2000000000000002,12.9],\"y\":[153796.31,49289.413499999995,90722.2016,104886.15929999998,74959.210000000006,91990.759999999995,8691.3403199999993,71101.327499999999,63546.809600000001,138866.62950000001,103245.92,169796.26000000001,45297.331200000001,108570.63039999999,12838.086720000001,150864.24339999998,63383.836500000005,111934.7392,122041.6384,13655.797919999999,69749.720000000001,42277.113600000004,200344.63819999999,55086.57450000001,49121.7408,90019.731199999995,14767.182720000001,142194.43350000001,176499.94,25630.437599999997,176922.51000000001,140041.91,55839.961600000002,16084.859039999999,218635.69950000002,25618.51008,235269.603,236223.63450000001,195304.54999999999,40557.6512,74063.001600000003,71472.825599999996,207785.88029999999,221756.64659999998,81665.708800000008,88569.910000000003,265063.61700000003,210454.17300000004,106745.9904,269901.77400000003,38247.449999999997,79832.533500000005,104305,63525.842799999991,60534.715500000006,163179.00599999999,174360.60000000001,9578.2089599999999,118686.52159999999,91274.020000000004,125494.56819999999,79409.555200000003,77578.252800000002,168115.63699999999,150343.10000000001,117385.0245,40835.542500000003,102727.02309999999,91869.090399999986,83830.521600000007,15084.84528,81348.729600000006,23403.254400000002,164553.37,59724.384000000005,209002.11059999999,97798.121299999984,258172.3395,64062.432000000001,151244.62399999998,110316.32640000001,94747.949999999997,100368.0012,146627.39999999999,187768.12,19747.2448,81190.240099999995,174429.84,180178.83899999998,28324.837440000003,70974.566399999996,35281.9787,78995.680000000008,195598.88100000002,58374.779999999999,20563.682400000002,161860.98999999999,16100.500319999999,56808.739999999998,96080.908800000005,171547.29450000002,141477.39000000001,6043.1011200000003,105419.8208,82630.937600000005,20485.926719999999,183704.61979999999,107673.07000000001,15321.27312,193273.76000000001,7949.311200000001,114587.60850000002,21109.25952,179606.6635,115824.07339999998,108093.25439999999,18228.301919999998,110316.77,124794.13769999998,146991.429,253297.5705,198422.28219999999,108911.94249999999,32058.758399999999,117901.06240000001,31622.752000000004,20274.981120000004,237175.47900000002],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(102,194,165,1)\",\"size\":10,\"opacity\":0.69999999999999996,\"line\":{\"color\":\"rgba(102,194,165,1)\"}},\"text\":[\"Стаж:  3.7  лет<br>Зарплата:  153796  USD<br>Уровень:  Начальный\",\"Стаж:  1  лет<br>Зарплата:  49289  USD<br>Уровень:  Начальный\",\"Стаж:  7.8  лет<br>Зарплата:  90722  USD<br>Уровень:  Начальный\",\"Стаж:  6.6  лет<br>Зарплата:  104886  USD<br>Уровень:  Начальный\",\"Стаж:  11.1  лет<br>Зарплата:  74959  USD<br>Уровень:  Начальный\",\"Стаж:  13.5  лет<br>Зарплата:  91991  USD<br>Уровень:  Начальный\",\"Стаж:  0.6  лет<br>Зарплата:  8691  USD<br>Уровень:  Начальный\",\"Стаж:  10  лет<br>Зарплата:  71101  USD<br>Уровень:  Начальный\",\"Стаж:  7  лет<br>Зарплата:  63547  USD<br>Уровень:  Начальный\",\"Стаж:  2.7  лет<br>Зарплата:  138867  USD<br>Уровень:  Начальный\",\"Стаж:  12.1  лет<br>Зарплата:  103246  USD<br>Уровень:  Начальный\",\"Стаж:  6.5  лет<br>Зарплата:  169796  USD<br>Уровень:  Начальный\",\"Стаж:  1.1  лет<br>Зарплата:  45297  USD<br>Уровень:  Начальный\",\"Стаж:  0.6  лет<br>Зарплата:  108571  USD<br>Уровень:  Начальный\",\"Стаж:  4.8  лет<br>Зарплата:  12838  USD<br>Уровень:  Начальный\",\"Стаж:  10.6  лет<br>Зарплата:  150864  USD<br>Уровень:  Начальный\",\"Стаж:  0.2  лет<br>Зарплата:  63384  USD<br>Уровень:  Начальный\",\"Стаж:  5.7  лет<br>Зарплата:  111935  USD<br>Уровень:  Начальный\",\"Стаж:  4.5  лет<br>Зарплата:  122042  USD<br>Уровень:  Начальный\",\"Стаж:  8.6  лет<br>Зарплата:  13656  USD<br>Уровень:  Начальный\",\"Стаж:  9.3  лет<br>Зарплата:  69750  USD<br>Уровень:  Начальный\",\"Стаж:  14.6  лет<br>Зарплата:  42277  USD<br>Уровень:  Начальный\",\"Стаж:  0.2  лет<br>Зарплата:  200345  USD<br>Уровень:  Начальный\",\"Стаж:  11.7  лет<br>Зарплата:  55087  USD<br>Уровень:  Начальный\",\"Стаж:  8.2  лет<br>Зарплата:  49122  USD<br>Уровень:  Начальный\",\"Стаж:  10.8  лет<br>Зарплата:  90020  USD<br>Уровень:  Начальный\",\"Стаж:  5.6  лет<br>Зарплата:  14767  USD<br>Уровень:  Начальный\",\"Стаж:  7.3  лет<br>Зарплата:  142194  USD<br>Уровень:  Начальный\",\"Стаж:  6.5  лет<br>Зарплата:  176500  USD<br>Уровень:  Начальный\",\"Стаж:  3.3  лет<br>Зарплата:  25630  USD<br>Уровень:  Начальный\",\"Стаж:  9.2  лет<br>Зарплата:  176923  USD<br>Уровень:  Начальный\",\"Стаж:  4.9  лет<br>Зарплата:  140042  USD<br>Уровень:  Начальный\",\"Стаж:  2  лет<br>Зарплата:  55840  USD<br>Уровень:  Начальный\",\"Стаж:  8.3  лет<br>Зарплата:  16085  USD<br>Уровень:  Начальный\",\"Стаж:  0.6  лет<br>Зарплата:  218636  USD<br>Уровень:  Начальный\",\"Стаж:  9.2  лет<br>Зарплата:  25619  USD<br>Уровень:  Начальный\",\"Стаж:  0.5  лет<br>Зарплата:  235270  USD<br>Уровень:  Начальный\",\"Стаж:  2.6  лет<br>Зарплата:  236224  USD<br>Уровень:  Начальный\",\"Стаж:  6.7  лет<br>Зарплата:  195305  USD<br>Уровень:  Начальный\",\"Стаж:  4.1  лет<br>Зарплата:  40558  USD<br>Уровень:  Начальный\",\"Стаж:  4.2  лет<br>Зарплата:  74063  USD<br>Уровень:  Начальный\",\"Стаж:  9.4  лет<br>Зарплата:  71473  USD<br>Уровень:  Начальный\",\"Стаж:  9.6  лет<br>Зарплата:  207786  USD<br>Уровень:  Начальный\",\"Стаж:  6.1  лет<br>Зарплата:  221757  USD<br>Уровень:  Начальный\",\"Стаж:  11.1  лет<br>Зарплата:  81666  USD<br>Уровень:  Начальный\",\"Стаж:  8.1  лет<br>Зарплата:  88570  USD<br>Уровень:  Начальный\",\"Стаж:  10.1  лет<br>Зарплата:  265064  USD<br>Уровень:  Начальный\",\"Стаж:  6.6  лет<br>Зарплата:  210454  USD<br>Уровень:  Начальный\",\"Стаж:  10.9  лет<br>Зарплата:  106746  USD<br>Уровень:  Начальный\",\"Стаж:  13.7  лет<br>Зарплата:  269902  USD<br>Уровень:  Начальный\",\"Стаж:  6.2  лет<br>Зарплата:  38247  USD<br>Уровень:  Начальный\",\"Стаж:  12.7  лет<br>Зарплата:  79833  USD<br>Уровень:  Начальный\",\"Стаж:  5.1  лет<br>Зарплата:  104305  USD<br>Уровень:  Начальный\",\"Стаж:  11.1  лет<br>Зарплата:  63526  USD<br>Уровень:  Начальный\",\"Стаж:  6.7  лет<br>Зарплата:  60535  USD<br>Уровень:  Начальный\",\"Стаж:  9.5  лет<br>Зарплата:  163179  USD<br>Уровень:  Начальный\",\"Стаж:  10.2  лет<br>Зарплата:  174361  USD<br>Уровень:  Начальный\",\"Стаж:  11.3  лет<br>Зарплата:  9578  USD<br>Уровень:  Начальный\",\"Стаж:  14.8  лет<br>Зарплата:  118687  USD<br>Уровень:  Начальный\",\"Стаж:  5.6  лет<br>Зарплата:  91274  USD<br>Уровень:  Начальный\",\"Стаж:  8.9  лет<br>Зарплата:  125495  USD<br>Уровень:  Начальный\",\"Стаж:  10.8  лет<br>Зарплата:  79410  USD<br>Уровень:  Начальный\",\"Стаж:  2.3  лет<br>Зарплата:  77578  USD<br>Уровень:  Начальный\",\"Стаж:  0.9  лет<br>Зарплата:  168116  USD<br>Уровень:  Начальный\",\"Стаж:  2.5  лет<br>Зарплата:  150343  USD<br>Уровень:  Начальный\",\"Стаж:  4.1  лет<br>Зарплата:  117385  USD<br>Уровень:  Начальный\",\"Стаж:  12.7  лет<br>Зарплата:  40836  USD<br>Уровень:  Начальный\",\"Стаж:  6.8  лет<br>Зарплата:  102727  USD<br>Уровень:  Начальный\",\"Стаж:  14.6  лет<br>Зарплата:  91869  USD<br>Уровень:  Начальный\",\"Стаж:  13.4  лет<br>Зарплата:  83831  USD<br>Уровень:  Начальный\",\"Стаж:  3.4  лет<br>Зарплата:  15085  USD<br>Уровень:  Начальный\",\"Стаж:  12  лет<br>Зарплата:  81349  USD<br>Уровень:  Начальный\",\"Стаж:  13  лет<br>Зарплата:  23403  USD<br>Уровень:  Начальный\",\"Стаж:  4.7  лет<br>Зарплата:  164553  USD<br>Уровень:  Начальный\",\"Стаж:  6.7  лет<br>Зарплата:  59724  USD<br>Уровень:  Начальный\",\"Стаж:  9  лет<br>Зарплата:  209002  USD<br>Уровень:  Начальный\",\"Стаж:  4.7  лет<br>Зарплата:  97798  USD<br>Уровень:  Начальный\",\"Стаж:  10.9  лет<br>Зарплата:  258172  USD<br>Уровень:  Начальный\",\"Стаж:  8.2  лет<br>Зарплата:  64062  USD<br>Уровень:  Начальный\",\"Стаж:  1.8  лет<br>Зарплата:  151245  USD<br>Уровень:  Начальный\",\"Стаж:  1.8  лет<br>Зарплата:  110316  USD<br>Уровень:  Начальный\",\"Стаж:  10.1  лет<br>Зарплата:  94748  USD<br>Уровень:  Начальный\",\"Стаж:  13.6  лет<br>Зарплата:  100368  USD<br>Уровень:  Начальный\",\"Стаж:  6.9  лет<br>Зарплата:  146627  USD<br>Уровень:  Начальный\",\"Стаж:  4.3  лет<br>Зарплата:  187768  USD<br>Уровень:  Начальный\",\"Стаж:  5.9  лет<br>Зарплата:  19747  USD<br>Уровень:  Начальный\",\"Стаж:  10.7  лет<br>Зарплата:  81190  USD<br>Уровень:  Начальный\",\"Стаж:  12.2  лет<br>Зарплата:  174430  USD<br>Уровень:  Начальный\",\"Стаж:  0.9  лет<br>Зарплата:  180179  USD<br>Уровень:  Начальный\",\"Стаж:  1.5  лет<br>Зарплата:  28325  USD<br>Уровень:  Начальный\",\"Стаж:  9  лет<br>Зарплата:  70975  USD<br>Уровень:  Начальный\",\"Стаж:  10.3  лет<br>Зарплата:  35282  USD<br>Уровень:  Начальный\",\"Стаж:  13.7  лет<br>Зарплата:  78996  USD<br>Уровень:  Начальный\",\"Стаж:  9.2  лет<br>Зарплата:  195599  USD<br>Уровень:  Начальный\",\"Стаж:  1.4  лет<br>Зарплата:  58375  USD<br>Уровень:  Начальный\",\"Стаж:  13  лет<br>Зарплата:  20564  USD<br>Уровень:  Начальный\",\"Стаж:  8.1  лет<br>Зарплата:  161861  USD<br>Уровень:  Начальный\",\"Стаж:  3  лет<br>Зарплата:  16101  USD<br>Уровень:  Начальный\",\"Стаж:  10.3  лет<br>Зарплата:  56809  USD<br>Уровень:  Начальный\",\"Стаж:  4.4  лет<br>Зарплата:  96081  USD<br>Уровень:  Начальный\",\"Стаж:  9.9  лет<br>Зарплата:  171547  USD<br>Уровень:  Начальный\",\"Стаж:  7  лет<br>Зарплата:  141477  USD<br>Уровень:  Начальный\",\"Стаж:  1.2  лет<br>Зарплата:  6043  USD<br>Уровень:  Начальный\",\"Стаж:  6  лет<br>Зарплата:  105420  USD<br>Уровень:  Начальный\",\"Стаж:  0.7  лет<br>Зарплата:  82631  USD<br>Уровень:  Начальный\",\"Стаж:  13  лет<br>Зарплата:  20486  USD<br>Уровень:  Начальный\",\"Стаж:  7.5  лет<br>Зарплата:  183705  USD<br>Уровень:  Начальный\",\"Стаж:  13.2  лет<br>Зарплата:  107673  USD<br>Уровень:  Начальный\",\"Стаж:  1.3  лет<br>Зарплата:  15321  USD<br>Уровень:  Начальный\",\"Стаж:  9.3  лет<br>Зарплата:  193274  USD<br>Уровень:  Начальный\",\"Стаж:  0.6  лет<br>Зарплата:  7949  USD<br>Уровень:  Начальный\",\"Стаж:  12.3  лет<br>Зарплата:  114588  USD<br>Уровень:  Начальный\",\"Стаж:  5.9  лет<br>Зарплата:  21109  USD<br>Уровень:  Начальный\",\"Стаж:  4.8  лет<br>Зарплата:  179607  USD<br>Уровень:  Начальный\",\"Стаж:  10.6  лет<br>Зарплата:  115824  USD<br>Уровень:  Начальный\",\"Стаж:  13.5  лет<br>Зарплата:  108093  USD<br>Уровень:  Начальный\",\"Стаж:  1.7  лет<br>Зарплата:  18228  USD<br>Уровень:  Начальный\",\"Стаж:  10.3  лет<br>Зарплата:  110317  USD<br>Уровень:  Начальный\",\"Стаж:  8.6  лет<br>Зарплата:  124794  USD<br>Уровень:  Начальный\",\"Стаж:  4.5  лет<br>Зарплата:  146991  USD<br>Уровень:  Начальный\",\"Стаж:  5.7  лет<br>Зарплата:  253298  USD<br>Уровень:  Начальный\",\"Стаж:  5.6  лет<br>Зарплата:  198422  USD<br>Уровень:  Начальный\",\"Стаж:  10.5  лет<br>Зарплата:  108912  USD<br>Уровень:  Начальный\",\"Стаж:  6.9  лет<br>Зарплата:  32059  USD<br>Уровень:  Начальный\",\"Стаж:  0.7  лет<br>Зарплата:  117901  USD<br>Уровень:  Начальный\",\"Стаж:  12  лет<br>Зарплата:  31623  USD<br>Уровень:  Начальный\",\"Стаж:  6.2  лет<br>Зарплата:  20275  USD<br>Уровень:  Начальный\",\"Стаж:  12.9  лет<br>Зарплата:  237175  USD<br>Уровень:  Начальный\"],\"type\":\"scatter\",\"name\":\"Начальный\",\"textfont\":{\"color\":\"rgba(102,194,165,1)\"},\"error_y\":{\"color\":\"rgba(102,194,165,1)\"},\"error_x\":{\"color\":\"rgba(102,194,165,1)\"},\"line\":{\"color\":\"rgba(102,194,165,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.3,11.6,12.9,14.300000000000001,14.199999999999999,6.2999999999999998,1.1000000000000001,1.3999999999999999,8.6999999999999993,13.199999999999999,4.9000000000000004,8.1999999999999993,8.5,13.9,7.2999999999999998,10,1.3,0.90000000000000002,7.5999999999999996,13,10.6,11.4,11.800000000000001,8.4000000000000004,9.1999999999999993,4.9000000000000004,7.9000000000000004,12.300000000000001,6.2999999999999998,5.2999999999999998,11.9,2.3999999999999999,2.2999999999999998,7.9000000000000004,13.199999999999999,12.1,12.4,6.7000000000000002,4.5999999999999996,7.9000000000000004,6.5999999999999996,13.800000000000001,12.5,2.2000000000000002,0.10000000000000001,14.800000000000001,13.800000000000001,2.1000000000000001,8.5,5.2999999999999998,13,5.5999999999999996,9.1999999999999993,11.300000000000001,6.2999999999999998,13.800000000000001,14.5,1.8,7.4000000000000004,3.7000000000000002,3.7000000000000002,4,5.7000000000000002,5.2999999999999998,10.800000000000001,1.3,12.300000000000001,3,9.0999999999999996,0.80000000000000004,13.5,6.0999999999999996,3.3999999999999999,10.9,12,9.1999999999999993,8.1999999999999993,1.5,6.7000000000000002,3.2000000000000002,2.8999999999999999,9.1999999999999993,11,2.1000000000000001,9.9000000000000004,14.5,2.1000000000000001,10.9,1.1000000000000001,4.5999999999999996,6.2999999999999998,11.800000000000001,11.800000000000001,4.4000000000000004,8.4000000000000004,13.800000000000001,3.7000000000000002,2.2000000000000002,4.9000000000000004,11.1,5.2999999999999998,13.6,13.6,10.9,9.3000000000000007,13.9,11.6,2.3999999999999999,6.7999999999999998,8.4000000000000004,13.4,8.5999999999999996,4.5,14.5,9.4000000000000004,12.6,9.1999999999999993,1.8,2.7000000000000002,9.3000000000000007,7.5,4.9000000000000004],\"y\":[99328.070399999997,47261.549399999989,113897.69,102161.1776,45406.828800000003,76610.905599999998,26484.6816,189020.17369999998,67009.149999999994,221429.18389999997,191977.61400000003,171109.65150000001,51457.57,48376.790000000001,95891.215500000006,21254.950080000002,24176.757599999997,170527.29999999999,27151.346879999997,131533.0735,50517.054000000004,45364.489999999998,97016.285599999988,25725.932799999999,111152.88320000001,23026.658400000004,140965.52850000001,51518.180299999993,57307.068599999999,65901.190400000007,170207.19919999997,27119.907360000005,141718.356,115098.867,27872.97552,123806.78889999999,180714.05100000004,83996.854999999996,193756.91400000002,158305.72,54899.200000000004,64567.239999999998,44226.0288,119083.712,6938.6832000000013,85859.353600000002,21602.594879999997,61464.806400000001,106749.8325,106831.9232,26811.457920000001,185636.25900000002,120186.41,206135.50399999996,112856.5632,148769.973,62393.006499999996,122658.5055,139909.383,86014.796799999996,40901.011200000001,53135.809199999989,147037.32889999999,153662.31900000002,63729.6512,123310.24200000001,54495.773999999998,137664.5355,63043.564800000007,97758.009000000005,133272.09829999998,140036.769,163903.31339999998,37573.855999999992,25183.048319999998,13616.298720000001,12676.42224,47914.321499999998,27925.814879999998,120644.99000000001,9724.8887999999988,16213.883039999999,61903.820800000001,93636.787200000006,91577.899999999994,123456.33279999999,109543.55839999999,43606.760000000002,6596.8703999999998,190784.0925,16402.826880000001,174687.9345,44515.001600000003,162396.03600000002,154024.94380000001,4851.2491200000004,48030.713600000003,107005.19850000001,101606.00850000001,174969.89999999999,12809.17152,8059.2998400000006,94112.294399999999,195172.27789999996,102154.28480000001,35479.019999999997,15080.279039999999,142530.93409999998,175643.91000000003,31653.292799999999,26951.225600000002,102752.0384,21003.530400000003,25990.265600000002,201659.92200000002,13734.88704,47231.446199999991,128725.281,94454.086400000015,197722.60000000001,234147.90150000004,67596.512000000002],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(252,141,98,1)\",\"size\":10,\"opacity\":0.69999999999999996,\"line\":{\"color\":\"rgba(252,141,98,1)\"}},\"text\":[\"Стаж:  1.3  лет<br>Зарплата:  99328  USD<br>Уровень:  Средний\",\"Стаж:  11.6  лет<br>Зарплата:  47262  USD<br>Уровень:  Средний\",\"Стаж:  12.9  лет<br>Зарплата:  113898  USD<br>Уровень:  Средний\",\"Стаж:  14.3  лет<br>Зарплата:  102161  USD<br>Уровень:  Средний\",\"Стаж:  14.2  лет<br>Зарплата:  45407  USD<br>Уровень:  Средний\",\"Стаж:  6.3  лет<br>Зарплата:  76611  USD<br>Уровень:  Средний\",\"Стаж:  1.1  лет<br>Зарплата:  26485  USD<br>Уровень:  Средний\",\"Стаж:  1.4  лет<br>Зарплата:  189020  USD<br>Уровень:  Средний\",\"Стаж:  8.7  лет<br>Зарплата:  67009  USD<br>Уровень:  Средний\",\"Стаж:  13.2  лет<br>Зарплата:  221429  USD<br>Уровень:  Средний\",\"Стаж:  4.9  лет<br>Зарплата:  191978  USD<br>Уровень:  Средний\",\"Стаж:  8.2  лет<br>Зарплата:  171110  USD<br>Уровень:  Средний\",\"Стаж:  8.5  лет<br>Зарплата:  51458  USD<br>Уровень:  Средний\",\"Стаж:  13.9  лет<br>Зарплата:  48377  USD<br>Уровень:  Средний\",\"Стаж:  7.3  лет<br>Зарплата:  95891  USD<br>Уровень:  Средний\",\"Стаж:  10  лет<br>Зарплата:  21255  USD<br>Уровень:  Средний\",\"Стаж:  1.3  лет<br>Зарплата:  24177  USD<br>Уровень:  Средний\",\"Стаж:  0.9  лет<br>Зарплата:  170527  USD<br>Уровень:  Средний\",\"Стаж:  7.6  лет<br>Зарплата:  27151  USD<br>Уровень:  Средний\",\"Стаж:  13  лет<br>Зарплата:  131533  USD<br>Уровень:  Средний\",\"Стаж:  10.6  лет<br>Зарплата:  50517  USD<br>Уровень:  Средний\",\"Стаж:  11.4  лет<br>Зарплата:  45364  USD<br>Уровень:  Средний\",\"Стаж:  11.8  лет<br>Зарплата:  97016  USD<br>Уровень:  Средний\",\"Стаж:  8.4  лет<br>Зарплата:  25726  USD<br>Уровень:  Средний\",\"Стаж:  9.2  лет<br>Зарплата:  111153  USD<br>Уровень:  Средний\",\"Стаж:  4.9  лет<br>Зарплата:  23027  USD<br>Уровень:  Средний\",\"Стаж:  7.9  лет<br>Зарплата:  140966  USD<br>Уровень:  Средний\",\"Стаж:  12.3  лет<br>Зарплата:  51518  USD<br>Уровень:  Средний\",\"Стаж:  6.3  лет<br>Зарплата:  57307  USD<br>Уровень:  Средний\",\"Стаж:  5.3  лет<br>Зарплата:  65901  USD<br>Уровень:  Средний\",\"Стаж:  11.9  лет<br>Зарплата:  170207  USD<br>Уровень:  Средний\",\"Стаж:  2.4  лет<br>Зарплата:  27120  USD<br>Уровень:  Средний\",\"Стаж:  2.3  лет<br>Зарплата:  141718  USD<br>Уровень:  Средний\",\"Стаж:  7.9  лет<br>Зарплата:  115099  USD<br>Уровень:  Средний\",\"Стаж:  13.2  лет<br>Зарплата:  27873  USD<br>Уровень:  Средний\",\"Стаж:  12.1  лет<br>Зарплата:  123807  USD<br>Уровень:  Средний\",\"Стаж:  12.4  лет<br>Зарплата:  180714  USD<br>Уровень:  Средний\",\"Стаж:  6.7  лет<br>Зарплата:  83997  USD<br>Уровень:  Средний\",\"Стаж:  4.6  лет<br>Зарплата:  193757  USD<br>Уровень:  Средний\",\"Стаж:  7.9  лет<br>Зарплата:  158306  USD<br>Уровень:  Средний\",\"Стаж:  6.6  лет<br>Зарплата:  54899  USD<br>Уровень:  Средний\",\"Стаж:  13.8  лет<br>Зарплата:  64567  USD<br>Уровень:  Средний\",\"Стаж:  12.5  лет<br>Зарплата:  44226  USD<br>Уровень:  Средний\",\"Стаж:  2.2  лет<br>Зарплата:  119084  USD<br>Уровень:  Средний\",\"Стаж:  0.1  лет<br>Зарплата:  6939  USD<br>Уровень:  Средний\",\"Стаж:  14.8  лет<br>Зарплата:  85859  USD<br>Уровень:  Средний\",\"Стаж:  13.8  лет<br>Зарплата:  21603  USD<br>Уровень:  Средний\",\"Стаж:  2.1  лет<br>Зарплата:  61465  USD<br>Уровень:  Средний\",\"Стаж:  8.5  лет<br>Зарплата:  106750  USD<br>Уровень:  Средний\",\"Стаж:  5.3  лет<br>Зарплата:  106832  USD<br>Уровень:  Средний\",\"Стаж:  13  лет<br>Зарплата:  26811  USD<br>Уровень:  Средний\",\"Стаж:  5.6  лет<br>Зарплата:  185636  USD<br>Уровень:  Средний\",\"Стаж:  9.2  лет<br>Зарплата:  120186  USD<br>Уровень:  Средний\",\"Стаж:  11.3  лет<br>Зарплата:  206136  USD<br>Уровень:  Средний\",\"Стаж:  6.3  лет<br>Зарплата:  112857  USD<br>Уровень:  Средний\",\"Стаж:  13.8  лет<br>Зарплата:  148770  USD<br>Уровень:  Средний\",\"Стаж:  14.5  лет<br>Зарплата:  62393  USD<br>Уровень:  Средний\",\"Стаж:  1.8  лет<br>Зарплата:  122659  USD<br>Уровень:  Средний\",\"Стаж:  7.4  лет<br>Зарплата:  139909  USD<br>Уровень:  Средний\",\"Стаж:  3.7  лет<br>Зарплата:  86015  USD<br>Уровень:  Средний\",\"Стаж:  3.7  лет<br>Зарплата:  40901  USD<br>Уровень:  Средний\",\"Стаж:  4  лет<br>Зарплата:  53136  USD<br>Уровень:  Средний\",\"Стаж:  5.7  лет<br>Зарплата:  147037  USD<br>Уровень:  Средний\",\"Стаж:  5.3  лет<br>Зарплата:  153662  USD<br>Уровень:  Средний\",\"Стаж:  10.8  лет<br>Зарплата:  63730  USD<br>Уровень:  Средний\",\"Стаж:  1.3  лет<br>Зарплата:  123310  USD<br>Уровень:  Средний\",\"Стаж:  12.3  лет<br>Зарплата:  54496  USD<br>Уровень:  Средний\",\"Стаж:  3  лет<br>Зарплата:  137665  USD<br>Уровень:  Средний\",\"Стаж:  9.1  лет<br>Зарплата:  63044  USD<br>Уровень:  Средний\",\"Стаж:  0.8  лет<br>Зарплата:  97758  USD<br>Уровень:  Средний\",\"Стаж:  13.5  лет<br>Зарплата:  133272  USD<br>Уровень:  Средний\",\"Стаж:  6.1  лет<br>Зарплата:  140037  USD<br>Уровень:  Средний\",\"Стаж:  3.4  лет<br>Зарплата:  163903  USD<br>Уровень:  Средний\",\"Стаж:  10.9  лет<br>Зарплата:  37574  USD<br>Уровень:  Средний\",\"Стаж:  12  лет<br>Зарплата:  25183  USD<br>Уровень:  Средний\",\"Стаж:  9.2  лет<br>Зарплата:  13616  USD<br>Уровень:  Средний\",\"Стаж:  8.2  лет<br>Зарплата:  12676  USD<br>Уровень:  Средний\",\"Стаж:  1.5  лет<br>Зарплата:  47914  USD<br>Уровень:  Средний\",\"Стаж:  6.7  лет<br>Зарплата:  27926  USD<br>Уровень:  Средний\",\"Стаж:  3.2  лет<br>Зарплата:  120645  USD<br>Уровень:  Средний\",\"Стаж:  2.9  лет<br>Зарплата:  9725  USD<br>Уровень:  Средний\",\"Стаж:  9.2  лет<br>Зарплата:  16214  USD<br>Уровень:  Средний\",\"Стаж:  11  лет<br>Зарплата:  61904  USD<br>Уровень:  Средний\",\"Стаж:  2.1  лет<br>Зарплата:  93637  USD<br>Уровень:  Средний\",\"Стаж:  9.9  лет<br>Зарплата:  91578  USD<br>Уровень:  Средний\",\"Стаж:  14.5  лет<br>Зарплата:  123456  USD<br>Уровень:  Средний\",\"Стаж:  2.1  лет<br>Зарплата:  109544  USD<br>Уровень:  Средний\",\"Стаж:  10.9  лет<br>Зарплата:  43607  USD<br>Уровень:  Средний\",\"Стаж:  1.1  лет<br>Зарплата:  6597  USD<br>Уровень:  Средний\",\"Стаж:  4.6  лет<br>Зарплата:  190784  USD<br>Уровень:  Средний\",\"Стаж:  6.3  лет<br>Зарплата:  16403  USD<br>Уровень:  Средний\",\"Стаж:  11.8  лет<br>Зарплата:  174688  USD<br>Уровень:  Средний\",\"Стаж:  11.8  лет<br>Зарплата:  44515  USD<br>Уровень:  Средний\",\"Стаж:  4.4  лет<br>Зарплата:  162396  USD<br>Уровень:  Средний\",\"Стаж:  8.4  лет<br>Зарплата:  154025  USD<br>Уровень:  Средний\",\"Стаж:  13.8  лет<br>Зарплата:  4851  USD<br>Уровень:  Средний\",\"Стаж:  3.7  лет<br>Зарплата:  48031  USD<br>Уровень:  Средний\",\"Стаж:  2.2  лет<br>Зарплата:  107005  USD<br>Уровень:  Средний\",\"Стаж:  4.9  лет<br>Зарплата:  101606  USD<br>Уровень:  Средний\",\"Стаж:  11.1  лет<br>Зарплата:  174970  USD<br>Уровень:  Средний\",\"Стаж:  5.3  лет<br>Зарплата:  12809  USD<br>Уровень:  Средний\",\"Стаж:  13.6  лет<br>Зарплата:  8059  USD<br>Уровень:  Средний\",\"Стаж:  13.6  лет<br>Зарплата:  94112  USD<br>Уровень:  Средний\",\"Стаж:  10.9  лет<br>Зарплата:  195172  USD<br>Уровень:  Средний\",\"Стаж:  9.3  лет<br>Зарплата:  102154  USD<br>Уровень:  Средний\",\"Стаж:  13.9  лет<br>Зарплата:  35479  USD<br>Уровень:  Средний\",\"Стаж:  11.6  лет<br>Зарплата:  15080  USD<br>Уровень:  Средний\",\"Стаж:  2.4  лет<br>Зарплата:  142531  USD<br>Уровень:  Средний\",\"Стаж:  6.8  лет<br>Зарплата:  175644  USD<br>Уровень:  Средний\",\"Стаж:  8.4  лет<br>Зарплата:  31653  USD<br>Уровень:  Средний\",\"Стаж:  13.4  лет<br>Зарплата:  26951  USD<br>Уровень:  Средний\",\"Стаж:  8.6  лет<br>Зарплата:  102752  USD<br>Уровень:  Средний\",\"Стаж:  4.5  лет<br>Зарплата:  21004  USD<br>Уровень:  Средний\",\"Стаж:  14.5  лет<br>Зарплата:  25990  USD<br>Уровень:  Средний\",\"Стаж:  9.4  лет<br>Зарплата:  201660  USD<br>Уровень:  Средний\",\"Стаж:  12.6  лет<br>Зарплата:  13735  USD<br>Уровень:  Средний\",\"Стаж:  9.2  лет<br>Зарплата:  47231  USD<br>Уровень:  Средний\",\"Стаж:  1.8  лет<br>Зарплата:  128725  USD<br>Уровень:  Средний\",\"Стаж:  2.7  лет<br>Зарплата:  94454  USD<br>Уровень:  Средний\",\"Стаж:  9.3  лет<br>Зарплата:  197723  USD<br>Уровень:  Средний\",\"Стаж:  7.5  лет<br>Зарплата:  234148  USD<br>Уровень:  Средний\",\"Стаж:  4.9  лет<br>Зарплата:  67597  USD<br>Уровень:  Средний\"],\"type\":\"scatter\",\"name\":\"Средний\",\"textfont\":{\"color\":\"rgba(252,141,98,1)\"},\"error_y\":{\"color\":\"rgba(252,141,98,1)\"},\"error_x\":{\"color\":\"rgba(252,141,98,1)\"},\"line\":{\"color\":\"rgba(252,141,98,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[9.0999999999999996,12.1,14.300000000000001,5.7000000000000002,7.5999999999999996,0.40000000000000002,0.80000000000000004,2.7000000000000002,9,4.4000000000000004,10.300000000000001,11.4,3.7000000000000002,3.2999999999999998,11,14.5,2.2999999999999998,8.5,7.9000000000000004,2.6000000000000001,3.5,14.4,1.8999999999999999,6.9000000000000004,12.6,5.0999999999999996,4.2999999999999998,9.9000000000000004,8.5999999999999996,1.8999999999999999,1.2,3.7000000000000002,6.7000000000000002,11.4,6,5.7000000000000002,12.4,7.2000000000000002,5.5999999999999996,0.5,14.800000000000001,13.5,6.5,7.2000000000000002,3,7.7999999999999998,11,14.199999999999999,5.5999999999999996,6.9000000000000004,11,13.5,14.199999999999999,3,4.0999999999999996,0.40000000000000002,10.6,1.6000000000000001,3.7000000000000002,11.800000000000001,4.7000000000000002,9.6999999999999993,12.800000000000001,1,12.6,3.2999999999999998,4,11.5,12.699999999999999,9.5,8.4000000000000004,0.10000000000000001,7.7000000000000002,6.5,3,9.6999999999999993,11,2.3999999999999999,1.3,8.4000000000000004,2.7999999999999998,2.8999999999999999,8.4000000000000004,7.2999999999999998,6.0999999999999996,7.7999999999999998,9,0.29999999999999999,9.9000000000000004,1.3999999999999999,12.4,0,6.2000000000000002,7.5,2.5,3.1000000000000001,9.9000000000000004,6.0999999999999996,10.4,8.6999999999999993,1.7,4.7000000000000002,6.2000000000000002,2.6000000000000001,4.0999999999999996,7.2999999999999998,3.7999999999999998,4.7000000000000002,1.2,2.6000000000000001,0.59999999999999998],\"y\":[143929.78,68938.169999999998,56886.82,163853.67000000001,25079.414400000001,188840.7297,70369.382400000002,16420.62384,83347.052800000005,125203.28960000002,176133.14000000001,214103.709,105906.97869999999,19180.9512,5136.76368,99474.628500000006,144918.14949999997,35072.917399999998,196212.59100000001,14235.190560000001,217974.70609999998,125268.33089999999,262586.35350000003,257866.37550000002,34791.879999999997,24023.7248,178607.18979999996,6831.5961599999991,105469.67999999999,106638.3936,37003.029999999999,260051.21550000002,15739.248960000001,172428.76789999998,40857.497599999995,81594.278399999996,125931.12109999999,76325.138099999982,143439.26850000001,189359.76000000001,91868.943499999994,26943.419519999999,61934.07959999999,149776.88959999999,58913.689599999998,99803.114199999982,30420.419999999998,36770.57,109068.4736,54810.342400000001,220593.87659999999,42333.246500000001,76232.5,33706.029999999999,155799.24750000003,95101.772799999992,21584.121600000002,43233.401600000005,36089.103799999997,118346.99000000001,4815.3009599999996,98493.376000000004,108159.26079999999,197572.81050000002,91567.425599999988,6506.0596800000003,116524.60160000001,95857.017600000006,192442.24309999996,99365.868800000011,7145.1201599999995,8259.5376000000015,26629.503839999998,129553.47900000001,41451.669999999998,139876.15729999999,173070.94500000001,134384.31,159729.17249999999,99212.889999999999,19320.80832,167950.5435,58472.6656,54569.824000000008,87882.547200000015,81607.399999999994,23068.477440000002,35753.843199999996,70593.710000000006,138953.67000000001,215880.30900000001,143201.19600000003,242412.38550000003,18149.067360000001,20364.433919999999,15854.738400000002,75317.026500000007,244201.20300000001,113382.88919999999,136843.59889999998,134771.78909999999,98889.587200000009,69354.060800000007,62911.566000000006,7564.5489600000001,84086.622199999998,75955.440000000002,166502.47159999999,25209.813599999998,102347.9936,225282.76200000002],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(141,160,203,1)\",\"size\":10,\"opacity\":0.69999999999999996,\"line\":{\"color\":\"rgba(141,160,203,1)\"}},\"text\":[\"Стаж:  9.1  лет<br>Зарплата:  143930  USD<br>Уровень:  Старший\",\"Стаж:  12.1  лет<br>Зарплата:  68938  USD<br>Уровень:  Старший\",\"Стаж:  14.3  лет<br>Зарплата:  56887  USD<br>Уровень:  Старший\",\"Стаж:  5.7  лет<br>Зарплата:  163854  USD<br>Уровень:  Старший\",\"Стаж:  7.6  лет<br>Зарплата:  25079  USD<br>Уровень:  Старший\",\"Стаж:  0.4  лет<br>Зарплата:  188841  USD<br>Уровень:  Старший\",\"Стаж:  0.8  лет<br>Зарплата:  70369  USD<br>Уровень:  Старший\",\"Стаж:  2.7  лет<br>Зарплата:  16421  USD<br>Уровень:  Старший\",\"Стаж:  9  лет<br>Зарплата:  83347  USD<br>Уровень:  Старший\",\"Стаж:  4.4  лет<br>Зарплата:  125203  USD<br>Уровень:  Старший\",\"Стаж:  10.3  лет<br>Зарплата:  176133  USD<br>Уровень:  Старший\",\"Стаж:  11.4  лет<br>Зарплата:  214104  USD<br>Уровень:  Старший\",\"Стаж:  3.7  лет<br>Зарплата:  105907  USD<br>Уровень:  Старший\",\"Стаж:  3.3  лет<br>Зарплата:  19181  USD<br>Уровень:  Старший\",\"Стаж:  11  лет<br>Зарплата:  5137  USD<br>Уровень:  Старший\",\"Стаж:  14.5  лет<br>Зарплата:  99475  USD<br>Уровень:  Старший\",\"Стаж:  2.3  лет<br>Зарплата:  144918  USD<br>Уровень:  Старший\",\"Стаж:  8.5  лет<br>Зарплата:  35073  USD<br>Уровень:  Старший\",\"Стаж:  7.9  лет<br>Зарплата:  196213  USD<br>Уровень:  Старший\",\"Стаж:  2.6  лет<br>Зарплата:  14235  USD<br>Уровень:  Старший\",\"Стаж:  3.5  лет<br>Зарплата:  217975  USD<br>Уровень:  Старший\",\"Стаж:  14.4  лет<br>Зарплата:  125268  USD<br>Уровень:  Старший\",\"Стаж:  1.9  лет<br>Зарплата:  262586  USD<br>Уровень:  Старший\",\"Стаж:  6.9  лет<br>Зарплата:  257866  USD<br>Уровень:  Старший\",\"Стаж:  12.6  лет<br>Зарплата:  34792  USD<br>Уровень:  Старший\",\"Стаж:  5.1  лет<br>Зарплата:  24024  USD<br>Уровень:  Старший\",\"Стаж:  4.3  лет<br>Зарплата:  178607  USD<br>Уровень:  Старший\",\"Стаж:  9.9  лет<br>Зарплата:  6832  USD<br>Уровень:  Старший\",\"Стаж:  8.6  лет<br>Зарплата:  105470  USD<br>Уровень:  Старший\",\"Стаж:  1.9  лет<br>Зарплата:  106638  USD<br>Уровень:  Старший\",\"Стаж:  1.2  лет<br>Зарплата:  37003  USD<br>Уровень:  Старший\",\"Стаж:  3.7  лет<br>Зарплата:  260051  USD<br>Уровень:  Старший\",\"Стаж:  6.7  лет<br>Зарплата:  15739  USD<br>Уровень:  Старший\",\"Стаж:  11.4  лет<br>Зарплата:  172429  USD<br>Уровень:  Старший\",\"Стаж:  6  лет<br>Зарплата:  40857  USD<br>Уровень:  Старший\",\"Стаж:  5.7  лет<br>Зарплата:  81594  USD<br>Уровень:  Старший\",\"Стаж:  12.4  лет<br>Зарплата:  125931  USD<br>Уровень:  Старший\",\"Стаж:  7.2  лет<br>Зарплата:  76325  USD<br>Уровень:  Старший\",\"Стаж:  5.6  лет<br>Зарплата:  143439  USD<br>Уровень:  Старший\",\"Стаж:  0.5  лет<br>Зарплата:  189360  USD<br>Уровень:  Старший\",\"Стаж:  14.8  лет<br>Зарплата:  91869  USD<br>Уровень:  Старший\",\"Стаж:  13.5  лет<br>Зарплата:  26943  USD<br>Уровень:  Старший\",\"Стаж:  6.5  лет<br>Зарплата:  61934  USD<br>Уровень:  Старший\",\"Стаж:  7.2  лет<br>Зарплата:  149777  USD<br>Уровень:  Старший\",\"Стаж:  3  лет<br>Зарплата:  58914  USD<br>Уровень:  Старший\",\"Стаж:  7.8  лет<br>Зарплата:  99803  USD<br>Уровень:  Старший\",\"Стаж:  11  лет<br>Зарплата:  30420  USD<br>Уровень:  Старший\",\"Стаж:  14.2  лет<br>Зарплата:  36771  USD<br>Уровень:  Старший\",\"Стаж:  5.6  лет<br>Зарплата:  109068  USD<br>Уровень:  Старший\",\"Стаж:  6.9  лет<br>Зарплата:  54810  USD<br>Уровень:  Старший\",\"Стаж:  11  лет<br>Зарплата:  220594  USD<br>Уровень:  Старший\",\"Стаж:  13.5  лет<br>Зарплата:  42333  USD<br>Уровень:  Старший\",\"Стаж:  14.2  лет<br>Зарплата:  76232  USD<br>Уровень:  Старший\",\"Стаж:  3  лет<br>Зарплата:  33706  USD<br>Уровень:  Старший\",\"Стаж:  4.1  лет<br>Зарплата:  155799  USD<br>Уровень:  Старший\",\"Стаж:  0.4  лет<br>Зарплата:  95102  USD<br>Уровень:  Старший\",\"Стаж:  10.6  лет<br>Зарплата:  21584  USD<br>Уровень:  Старший\",\"Стаж:  1.6  лет<br>Зарплата:  43233  USD<br>Уровень:  Старший\",\"Стаж:  3.7  лет<br>Зарплата:  36089  USD<br>Уровень:  Старший\",\"Стаж:  11.8  лет<br>Зарплата:  118347  USD<br>Уровень:  Старший\",\"Стаж:  4.7  лет<br>Зарплата:  4815  USD<br>Уровень:  Старший\",\"Стаж:  9.7  лет<br>Зарплата:  98493  USD<br>Уровень:  Старший\",\"Стаж:  12.8  лет<br>Зарплата:  108159  USD<br>Уровень:  Старший\",\"Стаж:  1  лет<br>Зарплата:  197573  USD<br>Уровень:  Старший\",\"Стаж:  12.6  лет<br>Зарплата:  91567  USD<br>Уровень:  Старший\",\"Стаж:  3.3  лет<br>Зарплата:  6506  USD<br>Уровень:  Старший\",\"Стаж:  4  лет<br>Зарплата:  116525  USD<br>Уровень:  Старший\",\"Стаж:  11.5  лет<br>Зарплата:  95857  USD<br>Уровень:  Старший\",\"Стаж:  12.7  лет<br>Зарплата:  192442  USD<br>Уровень:  Старший\",\"Стаж:  9.5  лет<br>Зарплата:  99366  USD<br>Уровень:  Старший\",\"Стаж:  8.4  лет<br>Зарплата:  7145  USD<br>Уровень:  Старший\",\"Стаж:  0.1  лет<br>Зарплата:  8260  USD<br>Уровень:  Старший\",\"Стаж:  7.7  лет<br>Зарплата:  26630  USD<br>Уровень:  Старший\",\"Стаж:  6.5  лет<br>Зарплата:  129553  USD<br>Уровень:  Старший\",\"Стаж:  3  лет<br>Зарплата:  41452  USD<br>Уровень:  Старший\",\"Стаж:  9.7  лет<br>Зарплата:  139876  USD<br>Уровень:  Старший\",\"Стаж:  11  лет<br>Зарплата:  173071  USD<br>Уровень:  Старший\",\"Стаж:  2.4  лет<br>Зарплата:  134384  USD<br>Уровень:  Старший\",\"Стаж:  1.3  лет<br>Зарплата:  159729  USD<br>Уровень:  Старший\",\"Стаж:  8.4  лет<br>Зарплата:  99213  USD<br>Уровень:  Старший\",\"Стаж:  2.8  лет<br>Зарплата:  19321  USD<br>Уровень:  Старший\",\"Стаж:  2.9  лет<br>Зарплата:  167951  USD<br>Уровень:  Старший\",\"Стаж:  8.4  лет<br>Зарплата:  58473  USD<br>Уровень:  Старший\",\"Стаж:  7.3  лет<br>Зарплата:  54570  USD<br>Уровень:  Старший\",\"Стаж:  6.1  лет<br>Зарплата:  87883  USD<br>Уровень:  Старший\",\"Стаж:  7.8  лет<br>Зарплата:  81607  USD<br>Уровень:  Старший\",\"Стаж:  9  лет<br>Зарплата:  23068  USD<br>Уровень:  Старший\",\"Стаж:  0.3  лет<br>Зарплата:  35754  USD<br>Уровень:  Старший\",\"Стаж:  9.9  лет<br>Зарплата:  70594  USD<br>Уровень:  Старший\",\"Стаж:  1.4  лет<br>Зарплата:  138954  USD<br>Уровень:  Старший\",\"Стаж:  12.4  лет<br>Зарплата:  215880  USD<br>Уровень:  Старший\",\"Стаж:  0  лет<br>Зарплата:  143201  USD<br>Уровень:  Старший\",\"Стаж:  6.2  лет<br>Зарплата:  242412  USD<br>Уровень:  Старший\",\"Стаж:  7.5  лет<br>Зарплата:  18149  USD<br>Уровень:  Старший\",\"Стаж:  2.5  лет<br>Зарплата:  20364  USD<br>Уровень:  Старший\",\"Стаж:  3.1  лет<br>Зарплата:  15855  USD<br>Уровень:  Старший\",\"Стаж:  9.9  лет<br>Зарплата:  75317  USD<br>Уровень:  Старший\",\"Стаж:  6.1  лет<br>Зарплата:  244201  USD<br>Уровень:  Старший\",\"Стаж:  10.4  лет<br>Зарплата:  113383  USD<br>Уровень:  Старший\",\"Стаж:  8.7  лет<br>Зарплата:  136844  USD<br>Уровень:  Старший\",\"Стаж:  1.7  лет<br>Зарплата:  134772  USD<br>Уровень:  Старший\",\"Стаж:  4.7  лет<br>Зарплата:  98890  USD<br>Уровень:  Старший\",\"Стаж:  6.2  лет<br>Зарплата:  69354  USD<br>Уровень:  Старший\",\"Стаж:  2.6  лет<br>Зарплата:  62912  USD<br>Уровень:  Старший\",\"Стаж:  4.1  лет<br>Зарплата:  7565  USD<br>Уровень:  Старший\",\"Стаж:  7.3  лет<br>Зарплата:  84087  USD<br>Уровень:  Старший\",\"Стаж:  3.8  лет<br>Зарплата:  75955  USD<br>Уровень:  Старший\",\"Стаж:  4.7  лет<br>Зарплата:  166502  USD<br>Уровень:  Старший\",\"Стаж:  1.2  лет<br>Зарплата:  25210  USD<br>Уровень:  Старший\",\"Стаж:  2.6  лет<br>Зарплата:  102348  USD<br>Уровень:  Старший\",\"Стаж:  0.6  лет<br>Зарплата:  225283  USD<br>Уровень:  Старший\"],\"type\":\"scatter\",\"name\":\"Старший\",\"textfont\":{\"color\":\"rgba(141,160,203,1)\"},\"error_y\":{\"color\":\"rgba(141,160,203,1)\"},\"error_x\":{\"color\":\"rgba(141,160,203,1)\"},\"line\":{\"color\":\"rgba(141,160,203,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[12.1,9.0999999999999996,2.1000000000000001,12.9,5.0999999999999996,12.5,13.9,0.10000000000000001,1.3999999999999999,14.199999999999999,10.6,7.0999999999999996,9.8000000000000007,6.7999999999999998,4.0999999999999996,11.300000000000001,10.9,4,1.8,3.7999999999999998,14.9,6.5999999999999996,1.7,5.2000000000000002,9.5999999999999996,0.20000000000000001,4.5999999999999996,13.300000000000001,1.5,15,5.5999999999999996,10.199999999999999,8.9000000000000004,4.5999999999999996,14.5,0.29999999999999999,14.699999999999999,10.4,1.8,12.5,4.7000000000000002,0.69999999999999996,11.5,14.699999999999999,8.4000000000000004,6.9000000000000004,14.1,12.9,4.5999999999999996,11.1,2.5,6.2000000000000002,4.5,3.6000000000000001,6.5,11.699999999999999,8.1999999999999993,10.4,2.7999999999999998,7.9000000000000004,12.6,10.699999999999999,3.1000000000000001,5.0999999999999996,6.5999999999999996,11,7.4000000000000004,3.7999999999999998,6.5,9,4.4000000000000004,7.0999999999999996,3.7999999999999998,8.6999999999999993,8.6999999999999993,2.1000000000000001,9.3000000000000007,7.0999999999999996,1.8,7.4000000000000004,1.1000000000000001,1.7,5.2000000000000002,11.300000000000001,12,11.699999999999999,4.0999999999999996,14.5,11.800000000000001,10,11.199999999999999,9.8000000000000007,7.5,8.5999999999999996,5.7000000000000002,10.5,13.699999999999999,14.9,4.2999999999999998,11.4,10.199999999999999,13.1,4.2000000000000002,14.6,5.5,0.69999999999999996,11.199999999999999,4.5999999999999996,6.2999999999999998,2,3,12.300000000000001,11.4,3,1.7,13.199999999999999,9.1999999999999993,7.9000000000000004,10.6,12.1,2.2999999999999998,10.6,1.7,1.5,11.800000000000001,8.1999999999999993,12.9,9.0999999999999996,5.2999999999999998,10.9,3.7999999999999998,3.8999999999999999,1.1000000000000001,7.2999999999999998,9.6999999999999993,2,1.1000000000000001,9.5,3.2999999999999998],\"y\":[15316.63776,13107.814560000003,15552.692639999999,46553.856,72143.949999999997,29852.467200000003,28440.360000000001,187933.12,183907.20000000001,31643.849999999999,62313.389999999999,92708.243200000012,110673.31869999999,211168.93050000002,170971.97189999997,27398.31552,129742.72200000001,66590.502399999998,92802.278299999991,61341.82,51552.019200000002,155358.36450000003,12019.38048,142982.63099999999,73345.513500000001,124445.376,53762.089999999997,176489.8749,27589.59072,193884.45000000001,121045.35139999999,214891.81200000001,11733.043680000001,13177.552319999999,163829.321,30892.700000000001,50491.147499999999,263969.56350000005,61304.224000000002,184821.09,99250.996199999994,9586.735200000001,25922.51568,92620.830000000002,27755.619839999999,80553.535999999993,16452.796319999998,25111.866239999999,17383.75488,141960.99599999998,22258.264319999998,19919.423999999999,142436.91809999998,51761.324800000002,122158.66499999999,107478.96750000001,156767.60250000001,61755.398399999998,187148.8824,100710.10800000001,7754.4590400000006,197637.8805,182898.8394,12223.739519999999,57765.961599999995,68920.970000000001,158029.21179999996,65957.919199999989,130622.28,51238.437499999993,165863.07999999999,111267.10800000001,235939.0275,96006.740000000005,113463.5968,201190.11549999999,47029.862400000005,7345.6070400000008,74860.42240000001,36648.646400000005,122499.72480000001,158543.40699999998,207266.62049999999,177800.66,58591.620000000003,71742.99519999999,222062.09689999997,14517.541439999999,123527.23,101020.30499999999,136379.15760000001,60382.815999999999,180819.23000000001,80709.063499999989,147353.49160000001,101516.28,82792.907799999986,13270.968000000001,41145.747200000005,142084.68579999998,185400.81759999998,72255.940299999987,126302.144,218569.95450000002,14579.395200000001,46505.977599999998,26050.69584,88808.774399999995,67500.710000000006,197853.89219999997,155395.23000000001,72324.473600000012,117365.74369999999,136012.80029999997,68344.748800000001,206140.2274,8269.4865599999994,25074.093599999997,203651.79789999998,55516.595199999996,188677.18800000002,18890.297279999999,96848.102400000003,70747.020000000004,21446.566559999999,18205.329599999997,59930.266500000005,92307.546000000017,208910.4345,95108.930999999997,9691.3123200000009,23153.911199999999,74029.360000000001,19757.505599999997,26053.600000000002,187364.84,106039.77629999998,60103.321399999993,14558.119200000001],\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(231,138,195,1)\",\"size\":10,\"opacity\":0.69999999999999996,\"line\":{\"color\":\"rgba(231,138,195,1)\"}},\"text\":[\"Стаж:  12.1  лет<br>Зарплата:  15317  USD<br>Уровень:  Ведущий\",\"Стаж:  9.1  лет<br>Зарплата:  13108  USD<br>Уровень:  Ведущий\",\"Стаж:  2.1  лет<br>Зарплата:  15553  USD<br>Уровень:  Ведущий\",\"Стаж:  12.9  лет<br>Зарплата:  46554  USD<br>Уровень:  Ведущий\",\"Стаж:  5.1  лет<br>Зарплата:  72144  USD<br>Уровень:  Ведущий\",\"Стаж:  12.5  лет<br>Зарплата:  29852  USD<br>Уровень:  Ведущий\",\"Стаж:  13.9  лет<br>Зарплата:  28440  USD<br>Уровень:  Ведущий\",\"Стаж:  0.1  лет<br>Зарплата:  187933  USD<br>Уровень:  Ведущий\",\"Стаж:  1.4  лет<br>Зарплата:  183907  USD<br>Уровень:  Ведущий\",\"Стаж:  14.2  лет<br>Зарплата:  31644  USD<br>Уровень:  Ведущий\",\"Стаж:  10.6  лет<br>Зарплата:  62313  USD<br>Уровень:  Ведущий\",\"Стаж:  7.1  лет<br>Зарплата:  92708  USD<br>Уровень:  Ведущий\",\"Стаж:  9.8  лет<br>Зарплата:  110673  USD<br>Уровень:  Ведущий\",\"Стаж:  6.8  лет<br>Зарплата:  211169  USD<br>Уровень:  Ведущий\",\"Стаж:  4.1  лет<br>Зарплата:  170972  USD<br>Уровень:  Ведущий\",\"Стаж:  11.3  лет<br>Зарплата:  27398  USD<br>Уровень:  Ведущий\",\"Стаж:  10.9  лет<br>Зарплата:  129743  USD<br>Уровень:  Ведущий\",\"Стаж:  4  лет<br>Зарплата:  66591  USD<br>Уровень:  Ведущий\",\"Стаж:  1.8  лет<br>Зарплата:  92802  USD<br>Уровень:  Ведущий\",\"Стаж:  3.8  лет<br>Зарплата:  61342  USD<br>Уровень:  Ведущий\",\"Стаж:  14.9  лет<br>Зарплата:  51552  USD<br>Уровень:  Ведущий\",\"Стаж:  6.6  лет<br>Зарплата:  155358  USD<br>Уровень:  Ведущий\",\"Стаж:  1.7  лет<br>Зарплата:  12019  USD<br>Уровень:  Ведущий\",\"Стаж:  5.2  лет<br>Зарплата:  142983  USD<br>Уровень:  Ведущий\",\"Стаж:  9.6  лет<br>Зарплата:  73346  USD<br>Уровень:  Ведущий\",\"Стаж:  0.2  лет<br>Зарплата:  124445  USD<br>Уровень:  Ведущий\",\"Стаж:  4.6  лет<br>Зарплата:  53762  USD<br>Уровень:  Ведущий\",\"Стаж:  13.3  лет<br>Зарплата:  176490  USD<br>Уровень:  Ведущий\",\"Стаж:  1.5  лет<br>Зарплата:  27590  USD<br>Уровень:  Ведущий\",\"Стаж:  15  лет<br>Зарплата:  193884  USD<br>Уровень:  Ведущий\",\"Стаж:  5.6  лет<br>Зарплата:  121045  USD<br>Уровень:  Ведущий\",\"Стаж:  10.2  лет<br>Зарплата:  214892  USD<br>Уровень:  Ведущий\",\"Стаж:  8.9  лет<br>Зарплата:  11733  USD<br>Уровень:  Ведущий\",\"Стаж:  4.6  лет<br>Зарплата:  13178  USD<br>Уровень:  Ведущий\",\"Стаж:  14.5  лет<br>Зарплата:  163829  USD<br>Уровень:  Ведущий\",\"Стаж:  0.3  лет<br>Зарплата:  30893  USD<br>Уровень:  Ведущий\",\"Стаж:  14.7  лет<br>Зарплата:  50491  USD<br>Уровень:  Ведущий\",\"Стаж:  10.4  лет<br>Зарплата:  263970  USD<br>Уровень:  Ведущий\",\"Стаж:  1.8  лет<br>Зарплата:  61304  USD<br>Уровень:  Ведущий\",\"Стаж:  12.5  лет<br>Зарплата:  184821  USD<br>Уровень:  Ведущий\",\"Стаж:  4.7  лет<br>Зарплата:  99251  USD<br>Уровень:  Ведущий\",\"Стаж:  0.7  лет<br>Зарплата:  9587  USD<br>Уровень:  Ведущий\",\"Стаж:  11.5  лет<br>Зарплата:  25923  USD<br>Уровень:  Ведущий\",\"Стаж:  14.7  лет<br>Зарплата:  92621  USD<br>Уровень:  Ведущий\",\"Стаж:  8.4  лет<br>Зарплата:  27756  USD<br>Уровень:  Ведущий\",\"Стаж:  6.9  лет<br>Зарплата:  80554  USD<br>Уровень:  Ведущий\",\"Стаж:  14.1  лет<br>Зарплата:  16453  USD<br>Уровень:  Ведущий\",\"Стаж:  12.9  лет<br>Зарплата:  25112  USD<br>Уровень:  Ведущий\",\"Стаж:  4.6  лет<br>Зарплата:  17384  USD<br>Уровень:  Ведущий\",\"Стаж:  11.1  лет<br>Зарплата:  141961  USD<br>Уровень:  Ведущий\",\"Стаж:  2.5  лет<br>Зарплата:  22258  USD<br>Уровень:  Ведущий\",\"Стаж:  6.2  лет<br>Зарплата:  19919  USD<br>Уровень:  Ведущий\",\"Стаж:  4.5  лет<br>Зарплата:  142437  USD<br>Уровень:  Ведущий\",\"Стаж:  3.6  лет<br>Зарплата:  51761  USD<br>Уровень:  Ведущий\",\"Стаж:  6.5  лет<br>Зарплата:  122159  USD<br>Уровень:  Ведущий\",\"Стаж:  11.7  лет<br>Зарплата:  107479  USD<br>Уровень:  Ведущий\",\"Стаж:  8.2  лет<br>Зарплата:  156768  USD<br>Уровень:  Ведущий\",\"Стаж:  10.4  лет<br>Зарплата:  61755  USD<br>Уровень:  Ведущий\",\"Стаж:  2.8  лет<br>Зарплата:  187149  USD<br>Уровень:  Ведущий\",\"Стаж:  7.9  лет<br>Зарплата:  100710  USD<br>Уровень:  Ведущий\",\"Стаж:  12.6  лет<br>Зарплата:  7754  USD<br>Уровень:  Ведущий\",\"Стаж:  10.7  лет<br>Зарплата:  197638  USD<br>Уровень:  Ведущий\",\"Стаж:  3.1  лет<br>Зарплата:  182899  USD<br>Уровень:  Ведущий\",\"Стаж:  5.1  лет<br>Зарплата:  12224  USD<br>Уровень:  Ведущий\",\"Стаж:  6.6  лет<br>Зарплата:  57766  USD<br>Уровень:  Ведущий\",\"Стаж:  11  лет<br>Зарплата:  68921  USD<br>Уровень:  Ведущий\",\"Стаж:  7.4  лет<br>Зарплата:  158029  USD<br>Уровень:  Ведущий\",\"Стаж:  3.8  лет<br>Зарплата:  65958  USD<br>Уровень:  Ведущий\",\"Стаж:  6.5  лет<br>Зарплата:  130622  USD<br>Уровень:  Ведущий\",\"Стаж:  9  лет<br>Зарплата:  51238  USD<br>Уровень:  Ведущий\",\"Стаж:  4.4  лет<br>Зарплата:  165863  USD<br>Уровень:  Ведущий\",\"Стаж:  7.1  лет<br>Зарплата:  111267  USD<br>Уровень:  Ведущий\",\"Стаж:  3.8  лет<br>Зарплата:  235939  USD<br>Уровень:  Ведущий\",\"Стаж:  8.7  лет<br>Зарплата:  96007  USD<br>Уровень:  Ведущий\",\"Стаж:  8.7  лет<br>Зарплата:  113464  USD<br>Уровень:  Ведущий\",\"Стаж:  2.1  лет<br>Зарплата:  201190  USD<br>Уровень:  Ведущий\",\"Стаж:  9.3  лет<br>Зарплата:  47030  USD<br>Уровень:  Ведущий\",\"Стаж:  7.1  лет<br>Зарплата:  7346  USD<br>Уровень:  Ведущий\",\"Стаж:  1.8  лет<br>Зарплата:  74860  USD<br>Уровень:  Ведущий\",\"Стаж:  7.4  лет<br>Зарплата:  36649  USD<br>Уровень:  Ведущий\",\"Стаж:  1.1  лет<br>Зарплата:  122500  USD<br>Уровень:  Ведущий\",\"Стаж:  1.7  лет<br>Зарплата:  158543  USD<br>Уровень:  Ведущий\",\"Стаж:  5.2  лет<br>Зарплата:  207267  USD<br>Уровень:  Ведущий\",\"Стаж:  11.3  лет<br>Зарплата:  177801  USD<br>Уровень:  Ведущий\",\"Стаж:  12  лет<br>Зарплата:  58592  USD<br>Уровень:  Ведущий\",\"Стаж:  11.7  лет<br>Зарплата:  71743  USD<br>Уровень:  Ведущий\",\"Стаж:  4.1  лет<br>Зарплата:  222062  USD<br>Уровень:  Ведущий\",\"Стаж:  14.5  лет<br>Зарплата:  14518  USD<br>Уровень:  Ведущий\",\"Стаж:  11.8  лет<br>Зарплата:  123527  USD<br>Уровень:  Ведущий\",\"Стаж:  10  лет<br>Зарплата:  101020  USD<br>Уровень:  Ведущий\",\"Стаж:  11.2  лет<br>Зарплата:  136379  USD<br>Уровень:  Ведущий\",\"Стаж:  9.8  лет<br>Зарплата:  60383  USD<br>Уровень:  Ведущий\",\"Стаж:  7.5  лет<br>Зарплата:  180819  USD<br>Уровень:  Ведущий\",\"Стаж:  8.6  лет<br>Зарплата:  80709  USD<br>Уровень:  Ведущий\",\"Стаж:  5.7  лет<br>Зарплата:  147353  USD<br>Уровень:  Ведущий\",\"Стаж:  10.5  лет<br>Зарплата:  101516  USD<br>Уровень:  Ведущий\",\"Стаж:  13.7  лет<br>Зарплата:  82793  USD<br>Уровень:  Ведущий\",\"Стаж:  14.9  лет<br>Зарплата:  13271  USD<br>Уровень:  Ведущий\",\"Стаж:  4.3  лет<br>Зарплата:  41146  USD<br>Уровень:  Ведущий\",\"Стаж:  11.4  лет<br>Зарплата:  142085  USD<br>Уровень:  Ведущий\",\"Стаж:  10.2  лет<br>Зарплата:  185401  USD<br>Уровень:  Ведущий\",\"Стаж:  13.1  лет<br>Зарплата:  72256  USD<br>Уровень:  Ведущий\",\"Стаж:  4.2  лет<br>Зарплата:  126302  USD<br>Уровень:  Ведущий\",\"Стаж:  14.6  лет<br>Зарплата:  218570  USD<br>Уровень:  Ведущий\",\"Стаж:  5.5  лет<br>Зарплата:  14579  USD<br>Уровень:  Ведущий\",\"Стаж:  0.7  лет<br>Зарплата:  46506  USD<br>Уровень:  Ведущий\",\"Стаж:  11.2  лет<br>Зарплата:  26051  USD<br>Уровень:  Ведущий\",\"Стаж:  4.6  лет<br>Зарплата:  88809  USD<br>Уровень:  Ведущий\",\"Стаж:  6.3  лет<br>Зарплата:  67501  USD<br>Уровень:  Ведущий\",\"Стаж:  2  лет<br>Зарплата:  197854  USD<br>Уровень:  Ведущий\",\"Стаж:  3  лет<br>Зарплата:  155395  USD<br>Уровень:  Ведущий\",\"Стаж:  12.3  лет<br>Зарплата:  72324  USD<br>Уровень:  Ведущий\",\"Стаж:  11.4  лет<br>Зарплата:  117366  USD<br>Уровень:  Ведущий\",\"Стаж:  3  лет<br>Зарплата:  136013  USD<br>Уровень:  Ведущий\",\"Стаж:  1.7  лет<br>Зарплата:  68345  USD<br>Уровень:  Ведущий\",\"Стаж:  13.2  лет<br>Зарплата:  206140  USD<br>Уровень:  Ведущий\",\"Стаж:  9.2  лет<br>Зарплата:  8269  USD<br>Уровень:  Ведущий\",\"Стаж:  7.9  лет<br>Зарплата:  25074  USD<br>Уровень:  Ведущий\",\"Стаж:  10.6  лет<br>Зарплата:  203652  USD<br>Уровень:  Ведущий\",\"Стаж:  12.1  лет<br>Зарплата:  55517  USD<br>Уровень:  Ведущий\",\"Стаж:  2.3  лет<br>Зарплата:  188677  USD<br>Уровень:  Ведущий\",\"Стаж:  10.6  лет<br>Зарплата:  18890  USD<br>Уровень:  Ведущий\",\"Стаж:  1.7  лет<br>Зарплата:  96848  USD<br>Уровень:  Ведущий\",\"Стаж:  1.5  лет<br>Зарплата:  70747  USD<br>Уровень:  Ведущий\",\"Стаж:  11.8  лет<br>Зарплата:  21447  USD<br>Уровень:  Ведущий\",\"Стаж:  8.2  лет<br>Зарплата:  18205  USD<br>Уровень:  Ведущий\",\"Стаж:  12.9  лет<br>Зарплата:  59930  USD<br>Уровень:  Ведущий\",\"Стаж:  9.1  лет<br>Зарплата:  92308  USD<br>Уровень:  Ведущий\",\"Стаж:  5.3  лет<br>Зарплата:  208910  USD<br>Уровень:  Ведущий\",\"Стаж:  10.9  лет<br>Зарплата:  95109  USD<br>Уровень:  Ведущий\",\"Стаж:  3.8  лет<br>Зарплата:  9691  USD<br>Уровень:  Ведущий\",\"Стаж:  3.9  лет<br>Зарплата:  23154  USD<br>Уровень:  Ведущий\",\"Стаж:  1.1  лет<br>Зарплата:  74029  USD<br>Уровень:  Ведущий\",\"Стаж:  7.3  лет<br>Зарплата:  19758  USD<br>Уровень:  Ведущий\",\"Стаж:  9.7  лет<br>Зарплата:  26054  USD<br>Уровень:  Ведущий\",\"Стаж:  2  лет<br>Зарплата:  187365  USD<br>Уровень:  Ведущий\",\"Стаж:  1.1  лет<br>Зарплата:  106040  USD<br>Уровень:  Ведущий\",\"Стаж:  9.5  лет<br>Зарплата:  60103  USD<br>Уровень:  Ведущий\",\"Стаж:  3.3  лет<br>Зарплата:  14558  USD<br>Уровень:  Ведущий\"],\"type\":\"scatter\",\"name\":\"Ведущий\",\"textfont\":{\"color\":\"rgba(231,138,195,1)\"},\"error_y\":{\"color\":\"rgba(231,138,195,1)\"},\"error_x\":{\"color\":\"rgba(231,138,195,1)\"},\"line\":{\"color\":\"rgba(231,138,195,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n-  С помощью графика можно понять, что зависимость между уровнем опыта/индустрией/зарплатой не наблюдается.\n\n### Взаимосвязь типа занятости и уровня опыта\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(stringr)\n\n# Шаг 1: Приведение к единому стилю написания\ndata_clean <- data_clean %>%\n  mutate(\n    `Employment Type` = str_to_title(str_trim(`Employment Type`)),\n    `Experience Level` = str_to_title(str_trim(`Experience Level`))\n  )\n\n# Шаг 2: Удаление аномалий — стажировка с Senior или Lead\ndata_clean <- data_clean %>%\n  filter(!( `Employment Type`== \"Internship\" & `Experience Level` %in% c(\"Senior\", \"Lead\")))\n\n# Шаг 3: Установка правильного порядка уровней\ndata_clean <- data_clean %>%\n  mutate(\n    `Experience Level` = factor(`Experience Level`, levels = c(\"Entry\", \"Mid\", \"Senior\", \"Lead\")),\n    `Employment Type` = factor(`Employment Type`, levels = c(\"Full-Time\", \"Part-Time\", \"Contract\", \"Internship\"))\n  )\n\n# Шаг 4: Построение графика\nggplot(\n  data_clean %>%\n    count(`Employment Type`, `Experience Level`),\n  aes(x = `Employment Type`, y = n, fill = `Experience Level`)\n) +\n  geom_col(position = \"dodge\") +\n  scale_x_discrete(labels = c(\n    \"Full-Time\" = \"Полная занятость\",\n    \"Part-Time\" = \"Частичная занятость\",\n    \"Contract\" = \"Контракт\",\n    \"Internship\" = \"Стажировка\"\n  )) +\n  labs(\n    title = \"Опыт и тип занятости\",\n    x = \"Тип занятости\",\n    y = \"Количество работников\",\n    fill = \"Уровень опыта\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}